### ISSUE TITLE
Mancata attribuzione a OSM - Azienda Trasporti Verona

### ISSUE THREAD

**Issue by Tresho** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#1]
# Descrizione
ATV pubblica tutte le deviazioni al normale tracciato delle proprie linee sul sito, corredandole con un'immagine della mappa senza i dovuti riferimenti.
Per risolvere basterebbe aggiungere l'attribuzione nel momento in cui "disegnano" sull'immagine.

## Riferimento del prodotto senza attibuzione
[Questa](https://www.atv.verona.it/flex/cm/pages/ServeBLOB.php/L/IT/IDPagina/2833) è una pagina come esempio, ma non l'unica (se si clicca sull'immagine viene ingrandita).

# Punto di contatto
atv@atv.verona.it - email generica
protocollo.atv@pec.it - posta elettronica certificata
info@atv.verona.it - ufficio informazioni
Pagina [segnalazioni e reclami](https://www.atv.verona.it/Segnalazioni_reclami)

**Comment by LorenzoStucchi** [comment]
Inviata segnalazione anche tramite il form per segnalazioni e reclami

**Comment by LorenzoStucchi** [comment]
Risposta:
```
La ringrazio per la segnalazione, ci stiamo attivando internamente per dare corso 
alle indicazioni relative all'attribuzione della mappa. Sarà mia cura darle 
comunicazione non appena avremo perfezionato il processo di adeguamento.
```

**Comment by Tresho** [comment]
Nelle ultime pagine di news hanno riportato i riferimenti corretti:
[Capolinea linea 61 "Zai" servizio estivo dal 28 giugno 2021](https://www.atv.verona.it/flex/cm/pages/ServeBLOB.php/L/IT/IDPagina/2853)
[Da mercoledì 30 giugno deviazione della linea 144 per lavori a Cerea](https://www.atv.verona.it/flex/cm/pages/ServeBLOB.php/L/IT/IDPagina/2855)
Sembrerebbe che si siano adeguati.

**Comment by LorenzoStucchi** [comment]
Avevo inviato ieri il sollecito, poichè erano passati 14 giorni dalla loro chiamata, con un esempio di come attribuire i dati. Hanno seguito l'esempio, molto bene.
Aspetto la loro comunicazione sulla correzione
