### ISSUE TITLE
Mancata attribuzione a OSM - primavercelli.it

### ISSUE THREAD

**Issue by musuruan** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#10]
# Descrizione
La mappa nell'articolo è priva di attribuzione.

## Riferimento del prodotto senza attibuzione
https://primavercelli.it/cronaca/attenzione-in-via-xx-settembre-semafori-guasti/

# Punto di contatto
https://primavercelli.it/contatti/

**Comment by LorenzoStucchi** [comment]
Risposta:

> Per come siamo organizzati ho potuto fare così, non abbiamo l'opzione di inserire link nelle foto in evidenza.
https://primavercelli.it/attualita/attenzione-in-via-xx-settembre-semafori-guasti/

Il risultato finale è accettabile ed è stato inserito anche un testo da informazioni sul progetto

![Mappa corretta PrimaVercelli](https://user-images.githubusercontent.com/29042221/127282858-c5ce5cd0-1f4e-4bad-8585-d18308ed8241.png)
