### ISSUE TITLE
Mancata attribuzione a OSM - insideevs.it 

### ISSUE THREAD

**Issue by e075e** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#101]
# Descrizione

immagine mappa di Chicago in un articolo online senza alcuna attribuzione 

## Riferimento del prodotto senza attribuzione

https://insideevs.it/news/705120/tesla-problemi-ricarica-supercharger-freddo

# Punto di contatto

redazione@insideevs.it

https://insideevs.it/info/contact

**Comment by LorenzoStucchi** [comment]
Risposta:

> Abbiamo inserito l'attribuzione "©OpenStreetMap contributors” nella mappa. Grazie per la segnalazione e per essere un nostro lettore. Ci scusiamo per l'inconveniente.

Mappa corretta:

![immagine](https://github.com/osmItalia/Segnalazioni-Mancata-attribuzione-OSM/assets/29042221/a168d799-642f-4065-a240-cbc133b8308f)
