### ISSUE TITLE
Mancata attribuzione a OSM - Concessionaria Grand Prix Group

### ISSUE THREAD

**Issue by FinixFighter** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#102]
# Descrizione
Manca attribuzionead OpenStreetMap nella mappa web utilizzata sul loro sito per indicare i vari punti vendita.

## Riferimento del prodotto senza attribuzione
https://www.grandprix.it/dove-siamo/

# Punto di contatto
E-mail inidicata sul sito web: info@grandprix.it
Numero Whatsapp: [+39 051 6044999](https://wa.me/+393666029108)
Numero di telefono: +39 051 6044999

**Comment by LorenzoStucchi** [comment]
Risposta:

Al fine di risolvere la problematica da Lei segnalata, abbiamo incluso i link necessari per il rispetto della licenza (in basso a destra). 
Aggiorni la cache del browser se non dovesse visualizzare subito l'integrazione.

Mappa corretta:
![immagine](https://github.com/osmItalia/Segnalazioni-Mancata-attribuzione-OSM/assets/29042221/af918240-3b99-4d3a-b99a-bf182d0fabb1)
