### ISSUE TITLE
Mancata attribuzione a OSM - Open Data Veneto

### ISSUE THREAD

**Issue by musuruan** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#103]
# Descrizione

Il sito Open Data Veneto usa OpenStreetMap come sfondo per mostrare i suoi dataset ma senza attribuzione

## Riferimento del prodotto senza attribuzione

Ad esempio, mappa dei numeri civici del Comune di Castelfranco Veneto:

![immagine](https://github.com/osmItalia/Segnalazioni-Mancata-attribuzione-OSM/assets/1221995/e3445c84-fbb8-4065-8872-5a62fd54ef3c)

Esempio link per Padova https://dati.veneto.it/custom_visualization/725923D2-EABF-7247-F6D9-9E1304E1D9B5

# Punto di contatto

opendata@regione.veneto.it

**Comment by LorenzoStucchi** [comment]
Invita segnalazione tramite canali di dialogo già esistenti con un direttore dell'unità Pianificazione Territoriale della provincia

/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
Nessuna risposta, inviata una seconda richiesta all'indirizzo segnalato

/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
Risposta:
> la ringraziamo per la segnalazione. Avviamo delle verifiche interne al termine delle quali seguiranno aggiornamenti.

**Comment by LorenzoStucchi** [comment]
Richieste altre informazioni 
/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
Risposta:
> abbiamo terminato le nostre verifiche e stiamo attualmente mettendo in atto le procedure necessarie per inserire il logo sulle mappe del portale.
> Vi aggiorneremo quanto prima.

**Comment by LorenzoStucchi** [comment]
Risposta con demo:

> abbiamo inserito il logo di OpenStreetMap (in basso a sinistra) sulle mappe del portale di Open Data Veneto per l’ambiente di collaudo.
> Vi mandiamo un esempio di come si vede:

![MicrosoftTeams-image](https://github.com/osmItalia/Segnalazioni-Mancata-attribuzione-OSM/assets/29042221/aed759a5-08d2-4051-981b-06e60f8b086d)

> Se la modifica così apportata per voi va bene, procediamo all'inserimento del logo anche in produzione.

**Comment by LorenzoStucchi** [comment]
Mappa corretta 

![immagine](https://github.com/osmItalia/Segnalazioni-Mancata-attribuzione-OSM/assets/29042221/0228b73b-d680-4e82-92ff-f99c4abb68f3)
