### ISSUE TITLE
Mancata attribuzione a OSM - Infomobilità L'Aquila

### ISSUE THREAD

**Issue by Robot8A** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#108]
# Descrizione
Infomobilità L'Aquila, router del trasporto pubblico. Sembra che utilizzi OpenTripPlanner come backend e Leaflet per visualizzare la mappa. La mappa di sfondo è OSM, e potrebbero esserlo anche i dati utilizzati per il percorso pedonale (il codice non sembra essere online).

## Riferimento del prodotto senza attribuzione
https://trasporti.opendatalaquila.it/infomobility
![Screenshot 2024-03-09 at 14-01-12 Infomobilità L'Aquila](https://github.com/osmItalia/Segnalazioni-Mancata-attribuzione-OSM/assets/19521377/d9f4c3e3-bad2-4d97-a74a-152930b0ca33)

# Punto di contatto
https://www.opendatalaquila.it/il-team/

**Comment by LorenzoStucchi** [comment]
Rispsta:

> Gentile Lorenzo, in realtà l'attribuzione è presente ma è stata nascosta dal footer dell'app web in una delle release, infatti sulla versione mobile è visibile. Ci scusiamo per questo inconveniente e ringrazio per avercelo segnalato. 
Sarà nostra cura aggiornare l'applicazione ASAP.

**Comment by LorenzoStucchi** [comment]
La mappa risulta ora correttamente attributita

![immagine](https://github.com/osmItalia/Segnalazioni-Mancata-attribuzione-OSM/assets/29042221/361e792b-e61e-4e60-a013-798183c55dd8)
