### ISSUE TITLE
Mancata attribuzione a OSM - [Chiavistello.it]

### ISSUE THREAD

**Issue by DoppioDanno** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#109]
# Descrizione
Il sito offre un servizio di self check-in in cui viene utilizzata la mappa OSM per visualizzare l'accesso alla struttura ricettiva. Non è presente l'attribuzione

## Riferimento del prodotto senza attribuzione
https://chiavistello.it/openmap/78104IiqpbjmgYMRzCYGOcH61pAa2TxuuoMy

# Punto di contatto
Chiavistello.it distribuito da hyppoCom S.r.l.
P.IVA IT02939661209
info@chiavistello.it - indirizzo presente nel sito web
tel:+390510826385

**Comment by LorenzoStucchi** [comment]
La mappa risulta ora correttamente attribuita 
![immagine](https://github.com/osmItalia/Segnalazioni-Mancata-attribuzione-OSM/assets/29042221/91cb5772-be0c-4adc-b2a4-40b694fa454c)

**Comment by DoppioDanno** [comment]
Grazie =)
