### ISSUE TITLE
Mancata attribuzione a OSM - Comune di Vercelli

### ISSUE THREAD

**Issue by musuruan** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#11]
# Descrizione

La mappa associata all'articolo è priva di attribuzione.

## Riferimento del prodotto senza attibuzione
https://comune.vercelli.it/articolo/guasto-temporaneo-ai-semafori-via-xx-settembre-si-raccomanda-prestare-massima-attenzione

# Punto di contatto

Piazza del Municipio 5
13100 Vercelli (VC)
Centralino 0161 5961
Fax 0161 596215

Posta Elettronica Certificata (PEC)
protocollo@cert.comune.vercelli.it

**Comment by LorenzoStucchi** [comment]
Nessuna risposta ancora ricevuta ma nell'articolo sotto l'immagine è stato inserito il testo con l'attribuzione.

![Articolo città vercelli](https://user-images.githubusercontent.com/29042221/127283311-1526196c-7980-430b-8bd2-986b449fe73a.png)

**Comment by LorenzoStucchi** [comment]
Ricevuta risposta:

> la ringrazio per la segnalazione, abbiamo provveduto immediatamente ad attribuire i crediti alla mappa utilizzata, nell'articolo sul sito www.comune.vercelli.it aggiungendo "©OpenStreetMap contributors" e sulla pagina Facebook citando il sito http://www.openstreetmap.org/ .
> 
> Ringraziando per la collaborazione si porgono i migliori saluti.

Link alla mappa su facebook https://www.facebook.com/comunevercelli/photos/a.747882508659654/4073274199453785/
