### ISSUE TITLE
Mancata attribuzione a OSM - Inps

### ISSUE THREAD

**Issue by FinixFighter** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#111]
# Descrizione
Le sedi dell'Inps possono essere ricercate sul sito, ed ognuna d iesse ha una sua pagina con una mappa che mostra l'ubicazione. Queste mappe non hanno attribuzione.

## Riferimento del prodotto senza attribuzione
Ecco un paio di esempi: 
1) https://www.inps.it/it/it/sedi-e-contatti/sedi/ricerca-sede/dettaglio-sedi.it.sezione-sedi.sedi-inps.600000.600000-elencoStruttureInps.html
2) https://www.inps.it/it/it/sedi-e-contatti/sedi/ricerca-sede/dettaglio-sedi.it.sezione-sedi.sedi-inps.550200.550200-elencoStruttureInps.html

# Punto di contatto
- Ci sono diverse PEC disponibili, che si trovano al link https://www.inps.it/it/it/sedi-e-contatti/contatti/pec.html

- Numero verde 803 164, gratuito da rete fissa, e dal numero 06 164 164 da cellulare a pagamento. Il servizio è attivo dal lunedì al venerdì, dalle 8 alle 20 e il sabato dalle 8 alle 14. (numeri present isu sito web https://www.inps.it/it/it/sedi-e-contatti/contatti/contact-center-multicanale.html)

- Pagina Twitter ufficiale dell'INPS: https://twitter.com/INPS_it 

- Form telematico tramite accesso alla propria area riservata MyINPS sul sito dell'ente.

**Comment by LorenzoStucchi** [comment]
Utilizzerei questo indirizzo:
Tecnologia, Informatica e Innovazione https://www.inps.it/it/it/l-istituto/struttura-organizzativa/direzioni-centrali/direzione-centrale-tecnologia--informatica-e-innovazione.html

PEC: dc.tecnologiainformaticaeinnovazione@postacert.inps.gov.it

/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
Risposta:

> scusandoci per l’errore, la informiamo che, come da screenshot  allegato, abbiamo provveduto alla corretta attribuzione a  "©OpenStreetMap contributors” della mappa esposta.

**Comment by LorenzoStucchi** [comment]
![immagine](https://github.com/osmItalia/Segnalazioni-Mancata-attribuzione-OSM/assets/29042221/508bf282-2d7e-4b90-8626-3686d23a77a9)
