### ISSUE TITLE
Mancata attribuzione a OSM - Infratel Italia

### ISSUE THREAD

**Issue by musuruan** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#112]
# Descrizione

Piano BUL: la nuova mappa interattiva disponibile sul sito web di Infratel Italia usa i dati di OSM (con un proprio tile server). Questa mappa non presenta alcuna attribuzione.

## Riferimento del prodotto senza attribuzione

https://webgis.infratelitalia.it/

# Punto di contatto

https://www.infratelitalia.it/contatti

**Comment by Martinligabue** [comment]
è stato già corretto

**Comment by musuruan** [comment]
Chiudo.
