### ISSUE TITLE
Mancata attribuzione a OSM - il fatto

### ISSUE THREAD

**Issue by e075e** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#114]
# Descrizione

Mancanza attribuzione su un immagine osm usata in un articolo online

## Riferimento del prodotto senza attribuzione

https://www.ilfattoquotidiano.it/2024/04/27/terremoto-campi-flegrei-gente-in-strada-paura-anche-a-napoli-non-ci-sono-danni/7528098/
# Punto di contatto

segreteriaweb@ilfattoquotidiano.it

**Comment by LorenzoStucchi** [comment]
![immagine](https://github.com/osmItalia/Segnalazioni-Mancata-attribuzione-OSM/assets/29042221/5b6e61db-ea59-4742-8f79-7286da78ae7b)
