### ISSUE TITLE
Mancata attribuzione a OSM - Associazione Amici di Chemp

### ISSUE THREAD

**Issue by musuruan** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#12]
# Descrizione

Le mappe scaricabili dalla seguente pagina web sono prive di attribuzione.
https://chemp.eu/arrivare/piedi

## Riferimento del prodotto senza attibuzione

https://chemp.eu/images/joomlaplates/file/190_C.pdf
https://chemp.eu/images/joomlaplates/img/190_A.jpg

# Punto di contatto

https://chemp.eu/associazione/contatti

**Comment by LorenzoStucchi** [comment]
Risposta:

> Ha perfettamente ragione, nel momento della creazione non è stato inserito e poi è rimasto così.
> Ho provveduto a modificare aggiungendo "©OpenStreetMap contributors" in basso a destra sulle tre immagini .
> ho anche aggiunto in fondo al testo la frase con il link:
> La mappa è stata predisposta utilizzando http://www.openstreetmap.org
> Può verificare se è tutto a posto?
> Mi scuso della dimenticanza.

Ho verificato e le mappe in JPG hanno l'attribuzione corretta ad esempio https://chemp.eu/images/joomlaplates/img/190_A.jpg ma le mappe nel pdf mancano dell'attribuzione

**Comment by LorenzoStucchi** [comment]
Risposta:

> Vero, modifico e appena sono a posto mando conferma
> Grazie

**Comment by LorenzoStucchi** [comment]
Risposta:

> Ho corretto anche i tre file pdf che avevano le cartine.
> Dovrebbe essere tutto a posto.

Ora tutte le mappe riportano l'attribuzione corretta
