### ISSUE TITLE
Mancata attribuzione a OSM - CENTRO FUNZIONALE REGIONALE REGIONE AUTONOMA VALLE D'AOSTA

### ISSUE THREAD

**Issue by musuruan** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#13]
# Descrizione

La mappa statica presente nella pagina web introduttiva del Portale dati e la mappa dinamica presente nel portale, sono mappe OSM e sono prive di attribuzione.

## Riferimento del prodotto senza attibuzione

https://cf.regione.vda.it/portale_dati.php
https://presidi2.regione.vda.it/str_dataview

# Punto di contatto

https://cf.regione.vda.it/contatti.php

**Comment by LorenzoStucchi** [comment]
Risposta:

> con la presente le comunico che abbiamo già provveduro a girare la sua comunicazione alla ditta che ci ha sviluppato il prodotto affinché inserisca i corretti riferimenti come da licenza. 
> Mi scuso per l'inconveniente.

**Comment by LorenzoStucchi** [comment]
Risposta:
> nella giornata di ieri abbiamo provveduto a inserire i riferimenti in mappa. 
> La videata ora si presenta come di seguito rappresentato con il link attivo per aprire la licenza di OpenStreetMap su una nuova scheda alla pagina https://www.openstreetmap.org/copyright. 
> In attesa di un suo cortese riscontro, porgo cordiali saluti.

**Comment by LorenzoStucchi** [comment]
La mappa risulta quindi attribuita correttamente

<img width="1280" alt="Portale attribuzione corretta" src="https://user-images.githubusercontent.com/29042221/127981925-c4972513-375f-403f-996c-b42c4d7d12e7.png">
