### ISSUE TITLE
Mancata attribuzione a OSM - Società di Navigazione Laghi

### ISSUE THREAD

**Issue by MarcoMinghini** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#15]
# Descrizione

Segnalo la totale mancanza di attribuzione nell'utilizzo della basemap OpenStreetMap da parte della app "DreamLake", recentemente rilasciata dalla Società di Navigazione Laghi (e ben in evidenza nel loro [sito](https://www.navigazionelaghi.it/)). La app esiste sia su Google Play (https://play.google.com/store/apps/details?id=it.navigazionelaghi.app) che su App Store (https://apps.apple.com/ca/app/dreamlake/id1527271571).

## Riferimento del prodotto senza attribuzione

La mancanza di attribuzione può essere verificata direttamente scaricando e installando la app; uno degli screenshot disponibili sulle pagine degli store (link sopra) è comunque sufficiente per verificare la mancanza di attribuzione.

# Punto di contatto

Sviluppatori app: ced.naviges@navigazionelaghi.it

Lago Maggiore: infomaggiore@navigazionelaghi.it | Lago di Garda: infogarda@navigazionelaghi.it | Lago di Como: infocomo@navigazionelaghi.it

**Comment by LorenzoStucchi** [comment]
Ciao @MarcoMinghini, tu hai modo di verificare se le modifiche richieste sono state implementate?
Vedo che entrambe le applicazioni hanno ricevuto un aggiornamento il 12 agosto che ha come descrizione  `Modifiche utilizzo mappa` È stato corretta l'attribuzione?

**Comment by LorenzoStucchi** [comment]
Ho avuto modo di controllare e le applicazioni sono state aggiornate e correttamente attribuite (l'interfaccia è praticamente uguale):

iOs 
![ios](https://user-images.githubusercontent.com/29042221/131706363-aa4e0fe8-746e-4fa7-9580-a12406350789.jpeg)

Android

![android](https://user-images.githubusercontent.com/29042221/131706411-5fbb592d-3689-4aa3-a215-7589a6037625.jpeg)

**Comment by MarcoMinghini** [comment]
Grazie @LorenzoStucchi per il grosso lavoro, sono contento che abbiano recepito e modificato!
