### ISSUE TITLE
Mancata attribuzione a OSM - Conitours

### ISSUE THREAD

**Issue by musuruan** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#17]
# Descrizione

Come riportato da [L’UNIONE MONREGALESE del 1 GIUGNO 2021 ](https://github.com/osmItalia/Segnalazioni-Mancata-attribuzione-OSM/files/6939400/11_011.pdf), il Conitours (Consorzio degli operatori turistici della provincia di Cuneo) ha realizzato 3 mappe tematiche in versione cartacea e pdf. La versione pedonale e auto sono prive dell'attribuzione; la versione per bike ha l'attribuzione ma non è corretta.

## Riferimento del prodotto senza attibuzione

https://www.cuneoalps.it/in-primo-piano/mondovie/mondovie-dintorni/pedonale
https://www.cuneoalps.it/images/pdf/pedonaledescrizionepdf%20PDF.pdf

https://www.cuneoalps.it/in-primo-piano/mondovie/mondovie-dintorni/bike
https://www.cuneoalps.it/images/pdf/bikedescrizione%20PDF.pdf

https://www.cuneoalps.it/in-primo-piano/mondovie/mondovie-dintorni/auto
https://www.cuneoalps.it/images/pdf/autodescriz%20PDF.pdf

# Punto di contatto

https://www.cuneoalps.it/chi-siamo

**Comment by LorenzoStucchi** [comment]
Ho segnalato principalmente che la versione pedonale manca di attribuzione e che le versioni auto e bike ne hanno un parziale (anche la versione auto ha l'attriubuzione parziale)

**Comment by musuruan** [comment]
Ciao Lorenzo. Dov'è l'attribuzione parziale nella versione auto?

**Comment by LorenzoStucchi** [comment]
> Ciao Lorenzo. Dov'è l'attribuzione parziale nella versione auto?

Ciao @musuruan , nella pagina web https://www.cuneoalps.it/in-primo-piano/mondovie/mondovie-dintorni/auto in basso c'è qualcosa di sfuocato che sembra l'attribuzione. Però probabilmente nel pdf è tagliata quella parte

**Comment by musuruan** [comment]
Grazie Lorenzo, non l'avevo notata. Purtroppo nel PDF non compare.

**Comment by LorenzoStucchi** [comment]
Inviata seconda segnalazione anche con riferimento al comune di Mondovì

**Comment by LorenzoStucchi** [comment]
Risposta:

> La ringraziamo per la sua segnalazione, provvederemo ad apportare le modifiche necessarie sui portali di nostro riferimento.
> Noi siamo un Consorzio senza scopo di lucro che opera per valorizzare il territorio e le sue imprese.
> La ringraziamo altresì per la sua disponibilità a supportarci nel caso di qualche nostra difficoltà.
> Cordialità

Confermo la disponibilità

**Comment by LorenzoStucchi** [comment]
Risposta:

> essendomi occupato in prima persona della creazione di questa cartina, mi sto ora prendendo cura delle correzioni da Lei giustamente richieste.
> In allegato trova i tre file delle mappe PEDONALE, CICLABILE e AUTO con indicazione: Copyright OpenStreetMap contributors.
> La prego di darmi gentile conferma che le tre mappe siano ora conformi al vostro regolamento per poterle caricare online.
> La stessa correzione è stata riportata sulle matrici per versione stampabili che trova anche in allegato.
> In attesa di un Suo riscontro porgo cordiali saluti.
> Comitato Tecnico Monregalese Conitours

Le immagini allegate riportano la corretta attribuzione

**Comment by LorenzoStucchi** [comment]
Risposta:

> Grazie per sollecita risposta
> Procediamo a caricarle online.

Ho controllato e le immagini sono corrette i pdf non ancora e sono link ai documenti vecchi

**Comment by LorenzoStucchi** [comment]
Risposta:

> abbiamo inserito online le mappe con correzioni come da Sua richiesta.
> Può verificare il tutto alla pagina:
> https://www.cuneoalps.it/in-primo-piano/mondovie/mondovie-dintorni

Ho controllato ed ora attribuita correttamente e in alcuni casi addiritura c'è due volte il riferimento
