### ISSUE TITLE
SalussolaNews

### ISSUE THREAD

**Issue by musuruan** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#18]
# Descrizione

Nell'articolo "Dalle stelle al cuore, gli astrofili vi raccontano il cielo di San Secondo" è presente una cartina OSM senza attribuzione.

## Riferimento del prodotto senza attibuzione

https://www.salussolanews.it/2021/08/20/dalle-stelle-al-cuore-gli-astrofili-vi-raccontano-il-cielo-di-san-secondo/

# Punto di contatto

https://www.salussolanews.it/contatti/

**Comment by LorenzoStucchi** [comment]
Prima risposta:

> Va bene, ma voi i dati dei nuovi nomi delle strade dove li avete presi visto che google non li riporta?. I miei dati sono miei. Buongiorno. 

Seconda risposta dopo circa un'ora:

> Buongiorno, riscrivo, non ho letto che bisognava citare la fonte e chiedo scusa.
> Comunque il link porta(va) alla vostra pagina e in nessun posto è era scritto che la cartina è mia nostra.
> Prima della mia nostra pubblicazione il 99,9% dei Salussolesi non sapeva dell'esistenza della vostra mappa cartina, quindi vi ho fatto un favore.
> Il mio nostro sito non è commerciale, come vede non c'è pubblicità, ed è auto finanziato, cioè non percepiamo nulla da nessuno, cioè pago io hard e softw e licenze varie.
> Voglio sottolineare quanto segue:
> La vostra cartina per quanto riguarda Salussola ha alcuni errori.
> Visto che di certo non conoscete Salussola e non siete venuti a controllare strada per strada, ubicazione di chiese e cascine e numeri civici, la mia domanda, i dati dove li avete presi?
> Alcuni e molti dati sono sulla mappa di Google, li inserisco io e li inseriamo noi.
> Altri dati, Google, come alcune nuove vie, continua a non inserirli sebbene la nostra insistenza, ma comunque c'è qualche cartina mappa dove ci sono, e non è la vostra.
> Anche su quella cartina mappa i data li ho inserito io noi.
> Tutte le foto che vede pubblicate sui giornali e o su Google sono mie, nostre anche se non è riportao l'autore o il sito, e di certo non andiamo a reclamare.
> Scusate, non userò non useremo più la vostra mappa e non ne daremo indicazioni ai Salussolesi.
> Grazie escusate.

La mappa non è più riportata nel sito. Sarei per proporre alla persona che ha risposto di suggerire ed indicare dove effetuare le correzioni ma visti i toni delle mail e la soluzione adottata non so se sia disponibile al dialogo. @musuruan che conosci di più la zona cosa risponderesti?

**Comment by musuruan** [comment]
Ciao Lorenzo. Io risponderei giusto per rettificare alcune cose:

- noi siamo ben felici se vengono usati i nostri dati A PATTO CHE sia messa l'attribuzione. Questo l'unico veicolo che abbiamo per farci conoscere (oltre che essere una violazione della nostra licenza). Lui sarebbe felice se un suo articolo fosse copiato e pubblicato su un giornale locale senza citarlo e/o pagarlo?
- se una nostra mappa è stata scelta per un articolo evidentemente dava un valore aggiunto che probabilmente altre mappe non danno (e di questo ne siamo felici).
- i  nostri dati sono raccolti da volontari e chiunque può contribuire, correggerli ed usarli gratuitamente. Non è così per altre mappe, come ad esempio quelle di Google.
- tra i nostri contributori, oltre a persone che vivono vicino a Salussola , ci sono persone che lavorano per il settore cartografico della Provincia di Biella e la Provincia stessa ha donato dei dati e partecipato alla loro importazione in OSM. E tutti sono venuti a Salussola a fare i rilevamenti.
- nonostante tutti i volontari prestino la massima attenzione a quello che viene messo dentro a OSM, degli errori possono inevitabilmente accadere. Ma come detto sopra, chiunque può correggerli. E, se non è in grado di correggerli, li può comunque segnalare usando la funzione "note" del sito.
- WMI è una associazione no profit...

**Comment by LorenzoStucchi** [comment]
Non essendo più la mappa presente e non avendo ricevuto più nessuna risposta credo si possa chiudere la issue.
@musuruan cosa ne pensi?

**Comment by musuruan** [comment]
Ok.
