### ISSUE TITLE
Mancata attribuzione a OSM - I giornali del Piemonte (sito della Regione Piemonte)

### ISSUE THREAD

**Issue by musuruan** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#2]
# Descrizione
Il sito I giornali del Piemonte offre la possibilità di consultare i giornali locali già digitalizzati pubblicati in Piemonte dal 1846 ad oggi. 

## Riferimento del prodotto senza attribuzione

1. Andare sul sito https://www.giornalidelpiemonte.it/
2. Cliccare sulla voce "elenco giornali"
3. Cliccare su "Mappa"

Compare una mappa web di OpenStreetMap priva dell'attribuzione (è presente solo la dicitura "Leaflet", cliccando sulla quale si accede alla pagina della libreria javascript).

# Punto di contatto
https://www.giornalidelpiemonte.it/content/contatti.php

**Comment by LorenzoStucchi** [comment]
![pagina corretta](https://user-images.githubusercontent.com/29042221/122890180-bd789d00-d343-11eb-8906-8ca2b2ae7e5a.png)

Dopo la segnalazione è stata corretta la pagina ed inserita l'attribuzione correttamente
