### ISSUE TITLE
Mancata attribuzione a OSM - Parco naturale regionale di Bracciano e Martignano

### ISSUE THREAD

**Issue by DinoM65** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#21]
# Descrizione
La nuova carta dei percorsi del Parco riporta il lavoro di mappatura presente in OSM senza citare la fonte. Prove sono: l'acquedotto di Traiano presente solo in OSM, i toponimi, la rete stradale secondaria e terziaria, le relazioni CAI. E' altamente probabile che tramite Qgis si sia sovrapposta la fotogrammetria con dati estratti da OSM tramite plugin. Si stanno organizzando eventi che presentano il lavoro ma in nessuno si cita che i dati della cartografia derivano da OSM, vedi: https://www.facebook.com/oriolo.romano/posts/4435315646511955?__tn__=-R e https://www.facebook.com/GruppoTuscia/photos/a.113007633631650/364221041843640/?type=3&theater. So anche che il TGR Lazio farà a breve un servizio ad hoc.
PS. Tra l'altro il lavoro di mappatura su OSM fatto dal CAI è misero perché il "mazzo" me lo sono fatto io in tutti questi anni...

## Riferimento del prodotto senza attribuzione
https://www.parcobracciano.it/it/vivere-il-parco/percorsi-e-sentieri/
https://www.parcobracciano.it/media/2243/bozza-cartografia-nuova-sentieristica-lug21.pdf

# Punto di contatto
mcatena@regione.lazio.it Massimo Catena, responsabile progetto sentieristica del parco

**Comment by LorenzoStucchi** [comment]
@DinoM65 Ho notato che in altre pagine come questa:
https://www.parcobracciano.it/it/vivere-il-parco/percorsi-e-sentieri/sentiero-martignano/
Viene utilizzata la mappa Apple che integra i dati di OSM, potrebbero i dati mostrati essere stati presi da lì

**Comment by DinoM65** [comment]
@LorenzoStucchi Nella segnalazione il problema di attribuzione è la mappa pdf che a breve sarà stampata in migliaia di copie su carta. Quello da te indicato è lapalissiano che non vi siano violazioni. La mappa Apple è solo una immagine satellitare con qualche waypoint, label e geometrie mentre nel pdf sono riportate geometrie presenti SOLO in OSM e mancanti nella mappa Apple, ad esempio:
- l'acquedotto di Trainano disegnato anni fa da Ted O'Neil che non è possibile vedere perché è sotterraneo;
- i percorsi della macchia grande di Manziana (disegnati da me);
- l'eliporto dell'ospedale di bracciano;
- la rotatoria in località la Rinascente tra la Settevene Palo-via Braccianese Claudia-via santa Lucia disegnata in OSM è evidente che nel PDF le strade sono quelle di OSM e non della mappa Apple;
- mentre nel PDF manca la nuova rotatoria ai Cappuccini (davanti la caserma CC di Bracciano) perché la mappa del parco è stata generata a novembre del 2020 mentre l'aggiornamento in OSM lo fatto solo recentemente; caso ancor più strano è che nella mappa Apple l'immagine satellitare non ha la rotatoria ma risulta disegnata una rotatoria (derivata da OSM?).
- le info dei toponimi dei rilievi, dei fossi dei passi sono identici a OSM;
- se confronto i dati nel territorio di Vejano come Monte Rosano e Antica via Clodia scopro che la quota proviene da OSM (diversa da IGM e CTR) e per la Clodia il name ora è description (tutte mie modifiche) desumo che la mappa in formato PDF del parco è stata generata la prima volta nel 2016 poi più volte aggiornata (ad es nuove rotatorie braccianese)
- sono presenti alberi secolari (ad es. il Carpino non presente in nessun altra cartografia) o alcuni fontanili (fonte Petrella, Vitabbia, fonte Natale) che sono stati mappati da me perché se ne era persa memoria o la carta IGM riportava in modo approssimativo
La mappa in PDF è derivata utilizzando geometrie estratte con Qgis da OSM.

**Comment by LorenzoStucchi** [comment]
La segnalazione è stata inviata e sono in attesa di una risposta, che se non arriverà in 14 giorni (come indicato dalla OSMF) invierò di nuovo. È non metto in dubbio che ci sono dati di OSM nella mappa.

Il mio commento era che può essere che non abbiano creato la mappa in QGIS, ma che siccome Apple Maps contiene i dati di OSM, abbiano usato un qualche tool per crearla. Non è chiaro quali dati di OSM siano usati in Apple Maps, alcuni servizi magari usano solo alcuni dati, mentre con altri c'è più profondità di dettagli.

**Comment by LorenzoStucchi** [comment]
Risposta:

> Le invio per conto del Direttore la foto dell'estratto della Bozza della nostra cartografia dove, nella legenda, è stato riportato quanto da voi richiesto.
> In prima analisi non era stato inserito in quanto gli shape scala 1:50.000 sono stati forniti dalla Regione Lazio di cui questo Ente fa parte.

![IMMAGINE BOZZA CARTOGRAFIA](https://user-images.githubusercontent.com/29042221/133410932-f095dee2-0527-4ba5-b9d9-f0889b68af9d.jpg)

confermo che è corretto e resto in attesa di vedere la mappa pubblicata

**Comment by LorenzoStucchi** [comment]
La mappa è stata corretta ora riporta l'attribuzione
https://www.parcobracciano.it/media/2294/cartografia-del-14092021.pdf

[cartografia-del-14092021.pdf](https://github.com/osmItalia/Segnalazioni-Mancata-attribuzione-OSM/files/7235223/cartografia-del-14092021.pdf)

![immagine](https://user-images.githubusercontent.com/29042221/134886740-7a6337e1-3017-4ce9-9e49-e7b34dbe0ee5.png)
