### ISSUE TITLE
Mancata attribuzione a OSM - datiopen.it

### ISSUE THREAD

**Issue by dieterdreist** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#24]
# Descrizione

mappa OSM come sfondo, senza Attribuzione

## Riferimento del prodotto senza attibuzione

http://www.datiopen.it/it/opendata/Regione_Lazio_Musei

# Punto di contatto

http://www.datiopen.it/it/chisiamo
info@datiopen.it

**Comment by LorenzoStucchi** [comment]
@dieterdreist ho trovato chi è il proprietario del dominio, se non rispondono alla mail possiamo provare contattando l'azienda direttamente

https://whois.domaintools.com/datiopen.it

**Comment by LorenzoStucchi** [comment]
Inviata nuova mail a info@sister.it con in copia supporto@sister.it

**Comment by LorenzoStucchi** [comment]
Risposta da responsabile sister:

> vi ringraziamo della vostra segnalazione. Conosciamo le vostre condizioni d’uso ed è nostra volontà attenerci ad esse. La dicitura relativa al vostro copyright è stata omessa per errore durante un aggiornamento software.
> Stiamo già lavorando per ripristinarla, sarà nostra premura notificarvi appena sarà nuovamente visibile online.

**Comment by LorenzoStucchi** [comment]
Mail conferma correzione:

> come da accordi le comunico che abbiamo risolto il problema ed ora la nostra mappa riporta nuovamente l’attribuzione a Open Street Map.
> Potrebbe essere necessario pulire la cache del suo browser per vedere la modifica.
> La ringrazio nuovamente per la sua segnalazione, cordiali saluti

Confermo che il sito ora riporta l'attribuzione corretta
![immagine](https://user-images.githubusercontent.com/29042221/141822958-627f1803-9a1f-4de5-9a69-008339461b06.png)
