### ISSUE TITLE
Mancata attribuzione a OSM - Corriere.it

### ISSUE THREAD

**Issue by mfortini** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#25]
Corriere.it ha croppato l'immagine di ingv del terremoto di Pesaro/Urbino, eliminando l'attribuzione

## Riferimento del prodotto senza attibuzione

https://www.corriere.it/cronache/21_ottobre_29/terremoto-ancona-oggi-204be6a8-38a7-11ec-8ce2-c94918111ac8.shtml

![immagine](https://user-images.githubusercontent.com/1104926/139430228-f2b65b70-4f93-4e99-9df4-28ca6755eb10.png)

Mappa originale:

http://terremoti.ingv.it/event/28753521

## Punto di contatto

https://twitter.com/corriere

**Comment by LorenzoStucchi** [comment]
Una attribuzione è stata inserita nella mappa dell'articolo, non è nella dicitura corretta però è una notevole passaggio. Cosa ne pensi @mfortini
<img width="593" alt="Schermata 2021-11-12 alle 14 55 52" src="https://user-images.githubusercontent.com/29042221/141479326-68b1cad0-5dde-424c-88c4-796ec0a00f87.png">

**Comment by mfortini** [comment]
@LorenzoStucchi la definirei un'attribuzione un po' di seconda mano, ma di fatto il risultato si può definire simile: vai su OSM e trovi il copyright dei dati originali, quindi direi OK

**Comment by LorenzoStucchi** [comment]
@mfortini concordo, non ho ricevuto una risposta alla mail, quindi se mandassi una nuova mail vuol dire ripartire da zero, non sapendo esattamente da quale canale sono arrivato a chi ha effettuato il cambio. 
L'ho indicato con il label attribuzione parziale e vedremo in caso di future situazioni simili che potranno ripresentarsi cosa andare a richiedere.
