### ISSUE TITLE
Mancata attribuzione a OSM - ilmeteo.it

### ISSUE THREAD

**Issue by opk12** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#26]
# Descrizione
Nel sito web, le slippy map OSM non hanno l'attribuzione, ma il solito link `Leaflet` in basso a destra.

## Riferimento del prodotto senza attibuzione
1. https://www.ilmeteo.it/portale/radar-italia
2. https://www.ilmeteo.it/meteo/Roma visitato da telefonino (la mappa non appare nella versione desktop)

# Punto di contatto
Incollo da https://www.ilmeteo.it/business/contatti
`info@ilmeteo.it` - Assistenza tecnica, commerciale e generica 
`tiziano@ilmeteo.it` - amministrazione
`redazione@ilmeteo.it`

**Comment by LorenzoStucchi** [comment]
Risposta:
> grazie per segnalazione, sistemiamo subito e mi scuso per non aver evidenziato la corretta attribuzione

**Comment by LorenzoStucchi** [comment]
Attribuzione corretta sul sito. @opk12 riesci a verificare sull'app e nel caso mandarmi uno screenshot?
![Screenshot 2021-11-10 at 09-24-21 Radar - Italia](https://user-images.githubusercontent.com/29042221/141076863-013261d8-23b4-40cd-92df-ffa682bde639.png)

**Comment by opk12** [comment]
Grazie. Non uso l'app. Segue uno screenshot di https://www.ilmeteo.it/meteo/Roma in Firefox Fennec.

![ilmeteo](https://user-images.githubusercontent.com/40740650/142256768-6443f250-93a5-4879-9c9f-3b9d48bbc423.png)

**Comment by LorenzoStucchi** [comment]
Ok perfetto anche qui c'è l'attribuzione 👍
