### ISSUE TITLE
Mancata attribuzione a OSM - turismo.marche.it

### ISSUE THREAD

**Issue by alesarrett** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#27]
# Descrizione
Il sito https://www.turismo.marche.it/ contiene una mappa con sfondo OpenStreetMap con un link "Attribution" che però punta alla pagina https://www.turismo.marche.it/ stessa.
All'interno di altre pagine del sito (e.g. https://www.turismo.marche.it/en-us/What-to-see/Tourist-attractions/Ripatransone-Luigi-Mercantini-Theatre/53) la mappa non ha nessun elemento che punti all'attribuzione a OSM.

## Riferimento del prodotto senza attibuzione
Tutte le mappe presenti all'interno del sito https://www.turismo.marche.it

# Punto di contatto
Si potrebbe provare tramite i contatti alla pagina https://www.turismo.marche.it/it-it/Accoglienza-e-Info/Contatti 

Per Informazioni Turistiche:
Numero verde: 800 222 111
Uffici di informazione turistica (IAT)
numeroverde.turismo@regione.marche.it
 
Per Informazioni Promozionali:
turismo.promozione@regione.marche.it
comunicazione.turismo@regione.marche.it
[Press room](https://www.regione.marche.it/Entra-in-Regione/Marche-Promozione/Press-Room)

**Comment by LorenzoStucchi** [comment]
Risposta:
> la ringraziamo per la segnalazione, abbiamo avvisato il servizio informatica che gestisce il sito, la terremo informata.

**Comment by LorenzoStucchi** [comment]
Risposta:
> ho corretto nelle mappe del sito turismo.marche.it l’attribuzione a openstreetmap.
> Resto a disposizione per eventuali ulteriori modifiche necessarie.

Ho controllato e tutte le mappe che ho visto hanno l'attribuzione corretta

![immagine](https://user-images.githubusercontent.com/29042221/142251424-aeb068ec-33b0-42f0-802a-d3e20303c2c1.png)
