### ISSUE TITLE
Mancata attribuzione a OSM - [Plot a route]

### ISSUE THREAD

**Issue by alesarrett** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#28]
# Descrizione
Il sito permette di creare percorso con base OpenStreetMap (es. https://www.plotaroute.com/route/1357290).
Le mappe prodotte riportano in basso a destra "Map data OpenStreetMap contributors" ma manca il link alla pagina di copyright.

## Riferimento del prodotto senza attibuzione
Mappe prodotte tramite https://www.plotaroute.com

# Punto di contatto
Non vedo e-mail in chiaro, c'è il form di contatto qui: https://www.plotaroute.com/contactus

**Comment by LorenzoStucchi** [comment]
È già presente una attribuzione parziale, la richiesta è di inserire l'url che rimandi al sito di OSM.

/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
Risposta:

> Thanks for flagging that up. The link used to be there so I’m not sure why it’s dropped off from this page but we’ll get it added back on asap.
> And thanks for your work in helping to providing such a great product – OpenStreetMap has revolutionised open access to global mapping.
