### ISSUE TITLE
Mancata attribuzione a OSM - [Paleorun]

### ISSUE THREAD

**Issue by alesarrett** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#29]
# Descrizione
Paleorun è un gruppo di podisti che nel loro sito hanno varie mappe con sfondo OSM. Le mappe sono create con https://www.plotaroute.com/, in cui OSM è citato ma in modo non completo (vedi https://github.com/osmItalia/Segnalazioni-Mancata-attribuzione-OSM/issues/28). Nelle pagine di paleorun comunque non appare in nessun modo il riferimento di OpenStreetMap.

## Riferimento del prodotto senza attibuzione
Mappe visibili su https://www.paleorun.it/

# Punto di contatto
Sul sito non ci sono e-mail di contatto visibili. La newsletter arriva dall'indirizzo news@paleorun.it
Nella pagina Facebook (https://www.facebook.com/paleorun.it/) però è presente l'indirizzo info@paleorun.it

**Comment by LorenzoStucchi** [comment]
Controllando il sito ho notato che le mappe senza attibuzione sono state rimosse ed è rimasta la webmap di plotaroute che riporta la corretta attribuzione,

![immagine](https://user-images.githubusercontent.com/29042221/144743665-8660638e-6339-4978-96d2-9edb53a32211.png)
