### ISSUE TITLE
Mancata attribuzione a OSM - WheelUp (magento2-module-store-locator? magento2-module-map?)

### ISSUE THREAD

**Issue by NonnEmilia** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#3]
# Descrizione
Sul sito di WheelUp si usa lo sfondo OSM senza alcuna attribuzione.

Controllando nel codice sembra che venga usato un plugin di Magento per gli store (`magento2-module-store-locator`) che a sua volta usa un altro plugin (`magento2-module-map`) per gestire le mappe.
Sulla pagina GitHub del plugin della mappa era stata aperta una issue riguardo l'impossiblità di inserire l'attribuzione tramite Leaflet: https://github.com/Smile-SA/magento2-module-map/issues/30
Nel repo del plugin store locator invece sembra sia stata aggiunta l'attribuzione a OSM dopo una segnalazione: https://github.com/Smile-SA/magento2-module-store-locator/issues/61

Non so come funzioni Magento, forse WheelUp deve "solo" aggiornare i plugin?

## Riferimento del prodotto senza attibuzione
- Mappa sul sito di WheelUp: https://www.wheelup.it/it/stores/
- Pagina GitHub del plugin magento2-module-store-locator: https://github.com/Smile-SA/magento2-module-store-locator
- Pagina GitHub del plugin magento2-module-map: https://github.com/Smile-SA/magento2-module-map

# Punto di contatto
Sul sito di WheelUp non ho trovato mail (se non quelle dell'assistenza clienti), ma nelle FAQ si rimanda al modulo di contatto: https://www.wheelup.it/it/contact ("Motivo di contatto": "Suggerimenti o reclami")

**Comment by LorenzoStucchi** [comment]
Inviata segnalazione anche tramite pec all'indirizzo omniaretail@pec.net

**Comment by LorenzoStucchi** [comment]
Risposta alla pec:

> Egregio,
> abbiamo preso in carico la sua richiesta e la stiamo gestendo per concludere l'intervento come da lei richiesto. 
> Le chiediamo di attendere in quanto in alta stagione i sistemisti sono impegnati.
> Per ulteriori richieste si prega di scrivere a:
> Alessandro Missaglia, sales101@wheelup.it
> Saluti

**Comment by LorenzoStucchi** [comment]
Facendo un controllo ho notato che è stata inserita l'attribuzione correttamente

![wheelup_attribution](https://user-images.githubusercontent.com/29042221/127515402-1759330b-99ec-4ad7-9dd7-1943c6f41655.png)
