### ISSUE TITLE
Mancata attribuzione a OSM - Pro Loco Candelo

### ISSUE THREAD

**Issue by musuruan** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#30]
# Descrizione

Su vari siti della Pro Loco Candelo compaiono diverse mappe (non aggiornate) prese da OSM senza la dovuta attribuzione. Avevo contattato l'ente in oggetto a novembre 2019, senza ricevere alcuna risposta.

In occasione di un nuovo evento organizzato a novembre e dicembre 2021, noto che questa brutta abitudine non è cessata.

## Riferimento del prodotto senza attibuzione

http://www.candeloeventi.it/borgo-di-babbo-natale-2021.html
http://www.candeloeventi.it/borgo-di-babbo-natale-2019.html
http://www.candeloeventi.it/borgo-di-babbo-natale-2017.html
http://www.candeloeventi.it/come-arrivare.html
http://www.prolococandelo.it/come-arrivare.html

# Punto di contatto

http://www.prolococandelo.it/contatti.html

**Comment by LorenzoStucchi** [comment]
Risposta:

> scusandoci per il disguido, abbiamo provveduto a inoltrare la sua richiesta a chi ci ha fornito le mappe (è una persona esterna alla nostra Associazione), in modo che possa provvedere a inserire i dovuti riferimenti.

**Comment by LorenzoStucchi** [comment]
Risposta:

> Buonasera,
> in questo periodo siamo alle prese con i mercatini natalizi.
> Provvederemo ad effettuare la correzione al termine dell'evento.
> Saluti
> La direzione

Ritengo la risposta non accettabile, in quanto è la stessa atitività che utilizza tramite per promozione la mappa di OpenStreetMap. Invio la mappa con l'attribuzione chiedendo che venga corretta al più presto.

**Comment by LorenzoStucchi** [comment]
Nuovo sollecito

/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
Nuovo sollecito

/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
Inviata nuova mail diretta espressamente al sindaco e al vicesindaco del comune di Candelo, in quanto patrocinano l'evento

/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
La mappa è stata rimossa e sostituita. Ora è presente una mappa che indica che i dati sono open data della provincia di Biella
