### ISSUE TITLE
Mancata attribuzione a OSM - 3bmeteo.com

### ISSUE THREAD

**Issue by ricloy** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#31]
# Descrizione
Sul sito web https://3bmeteo.com dell'azienda 3bmeteo S.r.l. vengono mostrate alcune mappe utilizzando Mapbox GL JS senza attribuire correttamente né Mapbox (che in certe condizioni potrebbe permetterlo) né OpenStreetMap. L'ingrandimento massimo è bloccato ad un valore piuttosto basso ma i dati della mappa sembrano essere OpenStreetMap. L' attribuzione manca sia sulla mappa stessa che in una pagina dedicata (comunque non corretto ma sempre meglio di niente).

## Riferimento del prodotto senza attribuzione

https://www.3bmeteo.com/radar/italia

In caso di fenomeni atmosferici avversi, una piccola mappa viene mostrata anche nella pagina del comune interessato. Ad esempio:
https://www.3bmeteo.com/meteo/firenze

# Punto di contatto

Nella pagina dei [termini di servizio](https://www.3bmeteo.com/termini-condizioni/it) è presente l'indirizzo email info@3bmeteo.com mentre su https://registroimprese.it si trova l'indirizzo PEC 3bmeteosrl@legalmail.it
Lo sviluppo software sembra venga effettuato internamente all'azienda (stando almeno alla lista del personale nella pagina [Chi siamo](https://www.3bmeteo.com/azienda))

**Comment by LorenzoStucchi** [comment]
Risposta:

> 
> Noi attualmente abbiamo acquistato una licenza per le mappe da quelli di https://www.maptiler.com/ quindi purtroppo non ci si è mai posti il problema che tali mappe potessero essere di OpenStreetMap e quelli di MapTiler non ci hanno mai comunicato questa cosa.
> 
> Abbiamo acquistato una licenza appositamente per evitare rischi di alcun tipo e per evitare violazioni o altro.
> 
> Il link per noi non è un problema e qualora avessimo usato OpenStreetMap ne saremmo stati subito forniti, ma per quanto concerne il nostro ambito e la sfera di conoscenza ci è completamente nuovo il fatto che Maptiler ci abbia venduto qualcosa non di loro proprietà.
> 
> Ci piacerebbe un attimo chiarire la questione perché ovviamente non è assolutamente nostro intento violare nulla e non mettere link, ma crediamo di essere nel giusto.
> 
> Apriamo un thread condiviso con quelli di Maptiler?
> Grazie e mi dispiace si sia incappati in questo disguido.

Serve approfondire il discorso sul funzionamento di Maptiler prima di rispondere

**Comment by LorenzoStucchi** [comment]
Ho controllato e Maptiler fornisce dei dati che possono essere utilizzati senza l'attribuzione ad OSM come riportato in questa [guida](https://documentation.maptiler.com/hc/en-us/articles/4410631040529-Get-a-map-without-the-OpenStreetMap-attribution). Tuttavia i dati presenti sul sito di 3bmeteo non ricade in questa categoria.

Invio questa guida che spiega come fare https://documentation.maptiler.com/hc/en-us/articles/4405445885457-How-to-add-MapTiler-attribution-to-a-map

**Comment by ricloy** [comment]
Grazie! Io non conosco maptiler; mi ero messo a spulciare le varie condizioni di utilizzo dei loro prodotti ma mi sono perso. Incrocio le dita con la speranza che il team 3bmeteo scelga di continuare a utilizzare OpenStreetMap aggiungendo l'attribuzione.

**Comment by LorenzoStucchi** [comment]
Risposta:

> Grazie mille per la spiegazione. I nostri referenti di maptiler ci avevano detto tutt'altro.
> Ma a questo punto mi domando. Cosa lo usiamo a fare maptiler se esiste anche un endpoint pubblico di openstreetmap che potremmo proxypassare e chiamare direttamente e poi mettere in cache per un anno in cdn?
> Oppure se questi dati sono liberamente scaricabili dal sito openstreetmap previa attribution?
> E' perseguibile anche questa via?
> Hai dei riferimenti a cose utilizzabili anche per scopi commerciali?
> Grazie mille dell'aiuto.
> Intanto apro un task per l'aggiunta dell'attribuzione.
> Scusa tanto per l'errore, ma eravamo assolutamente in buona fede.

Fornisco risposte alle domande

**Comment by LorenzoStucchi** [comment]
Mail da 3bmeteo:

> Abbiamo inserito l'attribution https://www.3bmeteo.com/radar/italia
> Grazie per la segnalazione e per la gentilezza.

Controllando non risulta nescuna attribuzione, chiedo chiarimenti

**Comment by LorenzoStucchi** [comment]
Ricaricando più volte è poi comparsa l'attribuizone

![immagine](https://user-images.githubusercontent.com/29042221/144271329-6fe49ab6-11f8-4c82-a3e1-e97b5d09b84a.png)
