### ISSUE TITLE
Mancata attribuzione a OSM - [BM Service]

### ISSUE THREAD

**Issue by cascafico** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#32]
# Descrizione

Mappa web senza attribuzione.

## Riferimento del prodotto senza attibuzione

https://zerowastefvg.it/mappa/

# Punto di contatto

info@bmservice.it - BM Service S.R.L.

**Comment by LorenzoStucchi** [comment]
L'attribuzione è stata inserita non nella mappa ma nel testo sottostante e riporta il testo e il link corretto

![immagine](https://user-images.githubusercontent.com/29042221/144743761-3b892983-a95a-4dbd-a9e9-5ad4173c921a.png)
