### ISSUE TITLE
Mancata attribuzione a OSM - Repubblica

### ISSUE THREAD

**Issue by mbranco2** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#33]
# Descrizione

La mappa è presente sulla prima pagina del sito web di Repubblica (18/12/21 h19), ed è ingrandita nella pagina dell'articolo

## Riferimento del prodotto senza attibuzione

https://milano.repubblica.it/cronaca/2021/12/18/news/geologo_andrea_zanchi_bicocca_terremoto-330676294/

# Punto di contatto

repubblicawww@repubblica.it

**Comment by LorenzoStucchi** [comment]
Altra violazione segnalata in #39 per l'articolo https://www.repubblica.it/esteri/2021/12/29/news/terremoto_grecia_creta_6_1-331984543/

**Comment by LorenzoStucchi** [comment]
Il primo articolo riporta ora una attribuzione corretta 

![immagine](https://user-images.githubusercontent.com/29042221/150181108-831a0692-10a3-44c8-a767-af9ebecaa53a.png)

Invio nuova segnalazione per il secondo articolo

**Comment by LorenzoStucchi** [comment]
Nuova segnalazione 
/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
Risposta:

> Buongiorno, dovrebbe inviare la mail alla redazione degli Esteri [esteridesk@repubblica.it](mailto:esteridesk@repubblica.it)

Inoltro la mail a questo indirizzo

**Comment by LorenzoStucchi** [comment]
Anche il secondo articolo ora riporta l'attribuzione, non è come richiesto ma è almeno un riferimento. 
![immagine](https://user-images.githubusercontent.com/29042221/156890329-f5e72b3f-b387-440c-9388-a5c7f9f6521a.png)
