### ISSUE TITLE
Mancata attribuzione a OSM - Open.online

### ISSUE THREAD

**Issue by zaffo80** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#38]
# Descrizione
Articolo su https://www.open.online/: La terra trema nel Catanese: più di 12 scosse di terremoto. La più forte di magnitudo 4.3

## Riferimento del prodotto senza attibuzione
https://www.open.online/2021/12/23/terremoto-sicilia-numerose-scosse-in-provincia-di-catania/

# Punto di contatto
0Redazione
Via Medici, n. 15 – 20123 – Milano
redazione@open.online

**Comment by LorenzoStucchi** [comment]
Stesso giornale di #34 integrata segnalazione con altra issue
