### ISSUE TITLE
Mancata attribuzione a OSM - La Repubblica

### ISSUE THREAD

**Issue by musuruan** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#39]
# Descrizione

La mappa a corredo dell'articolo è priva di attribuzione.

## Riferimento del prodotto senza attibuzione

https://www.repubblica.it/esteri/2021/12/29/news/terremoto_grecia_creta_6_1-331984543/

# Punto di contatto

repubblicawww@repubblica.it

**Comment by LorenzoStucchi** [comment]
Segnalazione da integrare con #33
