### ISSUE TITLE
Mancata attribuzione a OSM - Portale Turismo Regione Sardegna

### ISSUE THREAD

**Issue by LorenzoStucchi** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#4]
# Descrizione

Mancata attribuzione sul sito del portale del turismo

## Riferimento del prodotto senza attibuzione

https://www.sardegnaturismo.it/it/esplora/cannigione#mappe-contenuti-vicinanze

# Punto di contatto

tur.promozione@regione.sardegna.it - Ufficio promuzione turistica
tur.assessore@pec.regione.sardegna.it - Assessore turismo regione

**Comment by LorenzoStucchi** [comment]
Inviata segnalazione in data 26 Maggio 2021

**Comment by LorenzoStucchi** [comment]
Risposta ricevuta del 2 Luglio 2021:

> Innanzitutto ci scusiamo per il ritardo nella risposta e La ringraziamo per la segnalazione della nostra mancanza.
> 
> Intendiamo porre rimedio al più presto all’inconveniente da Lei segnalatoci, ossia che l’uso delle mappe pubblicate a corredo dei contenuti del portale SardegnaTurismo difetta della mancata attribuzione dei credit “©OpenStreetMap contributors”.
> 
> Attualmente siamo in fase di gara per il nuovo affidamento della manutenzione del portale SardegnaTurismo e degli altri sistemi informativi dell’Assessorato scrivente, una situazione che non ci ha permesso di intervenire immediatamente, dato che l’attuale società che gestisce i nostri sistemi si sta occupando esclusivamente della manutenzione ordinaria.
> In ogni caso stiamo valutando anche con loro un possibile intervento a breve termine, sul quale vi aggiorneremo.
> 
> Intanto, ringraziandola per la cortese proposta di aiuto per effettuare le modifiche, Le chiediamo quale possa essere per Voi una possibile soluzione immediata.
> 
> Cordiali saluti
>

**Comment by LorenzoStucchi** [comment]
Risposta inviata:

> La ringrazio per la risposta e comprendo la situazione.
> 
> La soluzione è spiegata anche nella guida dell’utilizzo della libreria [1]. La modifica in se non è particolarmente gravosa. L'attribuzione è automatica alla creazione della mappa. La società deve aver proceduto alla rimozione della attribuzione non seguendo le linee guida, riterrei quindi questa modifica come parte della manutenzione ordinaria.
> 
> Comprendendo però la situazione, richiederei, nel caso in cui le tempistiche di gara siano superiori al mese, di inserire un porzione di testo: “Dati delle mappa ©OpenStreetMap contributors” all’interno delle diverse pagine. Andando poi ad uniformare l’attribuzione al termine della gara.
> 
> Resto in attesa di vostri aggiornamenti.

**Comment by LorenzoStucchi** [comment]
Risposta ricevuta:

> provvederemo con immediatezza a verificare la possibilità di applicare la soluzione da Lei proposta.
> La terremo informata sugli sviluppi.
> Ringraziandola per la comprensione e per la preziosa collaborazione, Le porgo

**Comment by lucadelu** [comment]
Giusto per precisione nelle [note legali](https://www.sardegnaturismo.it/it/note-legali) viene correttamente citato OSM, anche se so che questo non è sufficiente

**Comment by LorenzoStucchi** [comment]
> Giusto per precisione nelle [note legali](https://www.sardegnaturismo.it/it/note-legali) viene correttamente citato OSM, anche se so che questo non è sufficiente

Può essere questa la soluzione temporanea che hanno adottato per segnalare che le mappe sono di OpenStreetMap, qui sotto il testo inserito.

> Le mappe dinamiche presenti su SardegnaTurismo utilizzano le cartografie del progetto OpenStreetMap  (© OpenStreetMap Contributors).

**Comment by LorenzoStucchi** [comment]
Risposta di soluzione da adottare:

> con la presente Le sottoponiamo una possibile soluzione, prospettataci dalla nostra software house, per l'inserimento dei credit di Open Street Map, nelle modalità  proposte.
> La prego volerla verificare e farci sapere se possiamo procedere con la richiesta di applicazione.

![ff483a82-229b-4c6c-ad99-f9bd1c5b4401](https://user-images.githubusercontent.com/29042221/127288895-e5d3faa7-84f6-480c-a144-797958c7fea7.jpg)

Ho rispondo indicando che la soluzione è corretta e che il testo deve puntare alla pagina https://www.openstreetmap.org/copyright

**Comment by LorenzoStucchi** [comment]
Controllando ho notato che ora è riportata l'attribuzione corretta.

![Schermata 2021-08-31 alle 18 51 28](https://user-images.githubusercontent.com/29042221/131543953-487bf213-14c3-409e-86c6-c27a1a520717.png)
