### ISSUE TITLE
Mancata attribuzione a OSM - Udine20

### ISSUE THREAD

**Issue by cascafico** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#41]
# Descrizione

Immagine mappa web da Protezione Civile FVG / Istituto Nazionale di Oceanografia e di Geofisica; attribuzione mancante, presumibilmente lasciata fuori con ritaglio.

## Riferimento del prodotto senza attibuzione

https://www.udine20.it/scossa-di-terremoto-magnituto-2-5-a-preone/2022/01/05/

# Punto di contatto

redazione@udine20.it Direttore resp. Fabio Di Bernardo

**Comment by LorenzoStucchi** [comment]
\remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
Riposta:

> Grazie della segnalazione, abbiamo inserito i riferimenti come da indicazioni

Nella mappa è stata inserita l'attribuzione

![immagine](https://user-images.githubusercontent.com/29042221/148640812-3ee3183e-765f-47ab-99c4-49ede15b2368.png)
