### ISSUE TITLE
Mancata attribuzione a OSM - www.repubblica.it

### ISSUE THREAD

**Issue by mbranco2** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#46]
# Descrizione

Mappa del terremoto in Calabria (20/1/22, h12,30)

## Riferimento del prodotto senza attibuzione

prima pagina : https://www.repstatic.it/content/nazionale/img/2022/01/20/111711938-444ae147-54a0-4dc9-8507-23a06e5f7a06.jpg?webp

articolo: https://www.repstatic.it/content/nazionale/img/2022/01/20/105330003-9f88b285-a579-4550-acfb-d63fe8bb4656.jpg?webp

# Punto di contatto

repubblicawww@repubblica.it

**Comment by LorenzoStucchi** [comment]
@mbranco2 vedo le immagini ma non l'articolo, era questo https://www.repubblica.it/cronaca/2022/01/20/news/ingv_terremoto_di_magnitudo_4_3_nella_costa_calabra_sud_occidentale-334545482/  a cui ora hanno tolto le immagini?

**Comment by mbranco2** [comment]
Sì, era quello.
Se si fa la ricerca "terremoto Calabria" sul sito di Repubblica, compare
con la cartina :-)

[image: image.png]

Il giorno ven 21 gen 2022 alle ore 17:28 Lorenzo Stucchi <
***@***.***> ha scritto:

**Comment by LorenzoStucchi** [comment]
Credo che l'immagine sia un refuso rimasto nell'articolo, non essendo direttamente nell'articolo non riuscirei ad avere un link da mandare. Inoltre, essendo ad una risoluzione così bassa è difficile da giustificare. Direi che hanno imparato la lezione dalle altre segnalazioni e non hanno inserito la mappa.

**Comment by mbranco2** [comment]
...o meglio, l'hanno tolta :-)
perché quel giorno e a quell'ora, la cartina era sia in prima pagina che
(più grande) nell'articolo...

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno lun 24 gen 2022 alle ore 18:22 Lorenzo Stucchi <
***@***.***> ha scritto:
