### ISSUE TITLE
Mancata attribuzione a OSM - [World Servizi Editoriali Srl]

### ISSUE THREAD

**Issue by FinixFighter** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#49]
Nella pagina https://www.cosedicasa.com/mercatini viene usata una foto si OSM senza attribuzione. Stessa cosa per tutti i mercatini elencati dal sito (basta provare ad espandere le singole regioni ed aprire il link di un mercatino).

## Riferimento del prodotto senza attibuzione
https://www.cosedicasa.com/mercatini

# Punto di contatto
Suppongo ci si debba rivolgere alla mail indicata nel sito: [redazione@cosedicasa.com](mailto:redazione@cosedicasa.com) (Tel: 02.63.675.307)

**Comment by LorenzoStucchi** [comment]
L'attribuzione è stata inserita in maniera corretta senza nessuna riposta alle mail 

![immagine](https://user-images.githubusercontent.com/29042221/165511725-84cbf705-e12e-47d3-944a-4dd784210c4b.png)
