### ISSUE TITLE
Mancata attribuzione a OSM - [Bakeca S.r.l.]

### ISSUE THREAD

**Issue by FinixFighter** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#51]
# Descrizione
I prodotti sul sito bakeca.it (ad esmpio case in affitto o in vendita) possono avere una posizione specifica, questa posizione viene visualizzata tramite OpenStreetMap, ma l'unica dicitura presente in basso a destra sulla mappa è "Leaflet".

## Riferimento del prodotto senza attibuzione
Ecco un paio di esempi:
-https://bologna.bakeca.it/dettaglio/vendita-case/csgl175bol-appartamento-in-v-f-barbieri-adze-v-corticella-nxvv241374728#annuncio_mappa
-https://firenze.bakeca.it/dettaglio/vendita-case/appartamento-di-3-vani-e-di-65-mq-firenze-rif-3a-m8vh235903698#annuncio_mappa

# Punto di contatto
Nella pagina contatti (https://www.bakeca.it/info/contattaci/) si trovano due mail: [risposte@bakeca.it](mailto:risposte@bakeca.it) per "amministrazione e contabilità", e [privacy@bakeca.it](mailto:privacy@bakeca.it) per "accertamenti e indagini di Polizia Giudiziaria".
Altrimenti si può compilare il form (sempre all'indirizzo https://www.bakeca.it/info/contattaci/).

**Comment by LorenzoStucchi** [comment]
Inviata segnalazione tramite form e tramite indirizzi mail

/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
Ricevuta conferma di ricezione del form

> La tua richiesta è stata ricevuta e verrà presa in carico il prima possibile.
> I nostri uffici sono aperti dal lunedì al venerdì dalle 9:30 alle 18:00.
> In caso di giorno festivo, la tua richiesta verrà presa in carico a partire dal primo giorno lavorativo utile.
> Intanto, puoi trovare alcune info veloci nella pagina delle nostre [Domande frequenti](https://www.bakeca.it/info/faq/)
>

**Comment by LorenzoStucchi** [comment]
Risposta:

> Nel ringraziarla per la sua cortese segnalazione, desideriamo informarla dell’avvenuto adeguamento delle note a margine delle mappe circa la proprietà intellettuale: siamo consapevoli degli sforzi prodotti dai contributori volti a raccogliere i dati e siamo pertanto più che lieti nel riconoscerne l’opera incorporando i necessari rimandi all’interno del nostro portale.
> 
> Le porgiamo un augurio di buon lavoro,

Mi risulta che l'attribuzione sia presente ai link segnalati, vedi immagine.

@FinixFighter riesci a darmi conferma che la vedi ovunque? 

![immagine](https://user-images.githubusercontent.com/29042221/161743718-0541e39c-00b6-41b5-bf1e-83e028cda71a.png)

**Comment by FinixFighter** [comment]
> Mi risulta che l'attribuzione sia presente ai link segnalati, vedi immagine.
> 
> @FinixFighter riesci a darmi conferma che la vedi ovunque?
> 
> ![immagine](https://user-images.githubusercontent.com/29042221/161743718-0541e39c-00b6-41b5-bf1e-83e028cda71a.png)
Ciao Lorenzo, si, ti confermo che ora l'attribuzione è corretta. Ho verificato anche in altre categorie del sito ed è tutto a posto! :D
