### ISSUE TITLE
Mancata attribuzione a OSM - Confindustria Novara Vercelli Valsesia

### ISSUE THREAD

**Issue by musuruan** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#52]
# Descrizione

In un comunicato stampa di Confindustria Novara Vercelli Valsesia compare una mappa OSM senza attribuzione. Questo comunicato è stato ripreso da varie testate locali.

La mappa è però correttamente attribuita nel webgis di cui si parla nell'articolo:
https://cnvv.studiososter.it/index.php/view/map/?repository=01&project=CNVV

## Riferimento del prodotto senza attibuzione

https://www.cnvv.it/notizia/27686/insediamenti-produttivi-nelle-province-di-novara-e/
(cliccare su "[Foto link a pagina webgis nella home page di www.cnvv.it](https://www.cnvv.it/notizia/27686/insediamenti-produttivi-nelle-province-di-novara-e/download/22567/)")

Testate che hanno ripreso la mappa senza attribuzione:
https://lasesia.vercelli.it/home/2022/04/06/news/mappa-on-line-per-scoprire-le-aree-libere-per-insediamenti-produttivi-111116/
https://www.infovercelli24.it/2022/04/06/leggi-notizia/argomenti/economia-3/articolo/cerchi-un-terreno-per-un-insediamento-una-mappa-online-offre-tutte-le-informazioni.html
https://tgvercelli.it/mappa-interattiva-confindustria-novara-vercelli-valsesia-permette-trovare-terreni-produttivi-cui-investire/

# Punto di contatto

https://www.cnvv.it/menu/contattaci/

Testate locali:
https://lasesia.vercelli.it/sezioni/74/contatti
infovc24@gmail.com
tgvercelli@gmail.com

# Correzioni

- [x] Cnvv
- [x] La sesia
- [x] Infovc24
- [x] TgVercelli.it

**Comment by LorenzoStucchi** [comment]
Inviata la segnalazione a tutti gli enti

/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
Tutti i prodotti sono stati correttamente attribuiti o rimossi
