### ISSUE TITLE
Mancata attribuzione a OSM - [Immobiliare.it S.p.A.]

### ISSUE THREAD

**Issue by FinixFighter** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#53]
# Descrizione
L'attribuzione manca solo in un determinato caso, ovvero quando si apre l'annuncio di una casa, scorrendo in basso si trova la mappa che mostra la posizione dell'immobile (e l'attribuzione è giusta), se si attiva la visualizzazione 3D l'attribuzione scompare.

## Riferimento del prodotto senza attibuzione
Esempio: https://www.immobiliare.it/annunci/94184478/ (ovviamente è sufficiente aprire un qualsiasi annuncio)..

# Punto di contatto
-Mail: [amministrazione@immobiliare.it](mailto:amministrazione@immobiliare.it) (fonte: https://www.immobiliare.it/terms/)
-Form di contatto: https://www.immobiliare.it/info/contattaci/

**Comment by opk12** [comment]
A me il 3D senza attribuzione compare per primo, e devo cliccare su 2D per vedere l'attribuzione, su desktop e mobile (Firefox ESR e Fennec Android).

Dicevo che necessita di un'attribuzione a sé proprio perché 1. è un rendering distinto 2. magari visualizza un altro database perché OSM non mappa le altezze.

**Comment by FinixFighter** [comment]
>2. magari visualizza un altro database perché OSM non mappa le altezze.

SI è vero, OSM non mappa le altezze, però gli edifici sono quelli (li riconosco perchè alcuni li ho mappati io e li conosco alla perfezione XD ); peraltro vedo che nella mia zona gli edifici vengono renderizzati tutti con la stessa altezza, anche se in realtà sono molto diversi tra loro, e anche se hanno il tag levels su OSM. Comunque i dati provengono da OSM, questo è certo.

**Comment by LorenzoStucchi** [comment]
Inviata segnalazione tramite mail e tramite form 

/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
Hanno risposto scusandosi dell'errore, la visualizazione 3D è nuova e ora hanno corretto e inserito l'attribuzione

![immagine](https://user-images.githubusercontent.com/29042221/164729586-74b80af7-afa5-4b1e-b48b-20f4e8413e01.png)
