### ISSUE TITLE
Mancata attribuzione a OSM - MotorK Italia Srl (per gruppofrentauto.com)

### ISSUE THREAD

**Issue by opk12** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#54]
# Descrizione
Sul sito web, la cartina a pie' di pagina è attribuita a `Leaflet | © MotorK`.

## Riferimento del prodotto senza attibuzione
https://www.gruppofrentauto.com/sedi/gruppo-frentauto-skoda-pescara/

# Punto di contatto
Il sito è realizzato da MotorK ([elenco delle sedi](https://www.motork.io/contacts/)).

italy@motork.io - Sede italiana

CC @FinixFighter

**Comment by LorenzoStucchi** [comment]
Inviata mail anche a info@gruppofrentauto.com

/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
Risposta:

> + Support Motork per risolvere il problema dell'attribuzione 
> Il nostro team ha cercato di aggiungere l'attribuzione, ma non è stato possibile. 
> I collegamenti delle mappe sono generati in automatico da MotorK e non abbiamo la possibilità di modificarli. 
> Ho messo in CC il supporto di MotorK che può aiutarci a risolvere questo problema. 

Come previsto non è il gruppo Frenauto in grado di risolvere il problema, loro stessi hanno contattato l'assistenza di MotorK

**Comment by LorenzoStucchi** [comment]
Risposta da MotorK:

> verifichiamo subito con il team di prodotto e tecnico la mancanza di attribuzione sulle mappe.
> Vi do riscontro non appena ho aggiornamenti.

**Comment by LorenzoStucchi** [comment]
Una prima parte è stata corretta come in immagine. Ho segnalato anche che il box copre l'attribuzione della mappa sopra

/remind me in 1 week

**Comment by LorenzoStucchi** [comment]
Anche la parte superiore dell'immagine è stata modifica, ora il banner è stato posizionato sotto la mappa, come visibile nell'immagine

![immagine](https://user-images.githubusercontent.com/29042221/174599613-82a2a0a3-051d-49e4-8780-d8a75c361bb5.png)

**Comment by LorenzoStucchi** [comment]
Risposta:

> scusandoci per il ritardo le confermo che abbiamo provveduto a sistemare anche le pagine della concessionaria come ad esempio:
> https://www.gruppofrentauto.com/sedi/gruppo-frentauto-skoda-pescara/ 
>  
> Abbiamo mantenuto i credits sulla desta ma abbiamo fatto in modo che il form non andasse più a coprirli.
>  
> Un cordiale saluto.
