### ISSUE TITLE
Mancata attribuzione a OSM - trovacasa.it

### ISSUE THREAD

**Issue by opk12** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#55]
# Descrizione
La cartina sul sito web non ha l'attribuzione.

## Riferimento del prodotto senza attibuzione
https://www.trovacasa.it/annunci/pe-tc-536-54081434

# Punto di contatto
[Form di contatto](https://www.trovacasa.it/info/contatti)

Altrimenti ci sarebbe l'email di Mediacom Srl (comproprietaria del sito, azienda di consulenza e sviluppo software) nella [privacy policy](https://www.trovacasa.it/info/privacy-policy). L'altra comproprietaria Immobiliare.it è stata contattata nella issue #53

Segnalazione originaria di @FinixFighter

**Comment by LorenzoStucchi** [comment]
cambio riferimento ad articolo https://www.trovacasa.it/annunci/mi-tc-58470-53838408#mappa

/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
Risposta:

> Mi scuso per il ritardo nella risposta e per la mancanza di attribuzione sulle mappe di TrovaCasa.
> Durante una modifica ai file JS avvenuta nel mese di aprile, l'attribuzione è saltata a causa di una configurazione modificata per errore da un mio collega.
> Abbiamo provveduto a ripristinare l'attribuzione e ora è correttamente visibile.
> es: https://www.trovacasa.it/annunci/rm-tc-8097-52767129

Ora risulta corretta

![immagine](https://user-images.githubusercontent.com/29042221/174302332-d0b330d9-3e4a-464d-8f57-17599ee4518d.png)
