### ISSUE TITLE
Mancata attribuzione a OSM - tuttocampo.it

### ISSUE THREAD

**Issue by Tresho** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#56]
# Descrizione

Il sito tuttocampo.it utilizza la mappa di openstreetmap senza attribuzione per mostrare la posizione dello stadio di ogni squadra.

## Riferimento del prodotto senza attibuzione
[Questa](https://www.tuttocampo.it/Italia/SerieA/GironeUnico/Squadra/HellasVerona/1009575/Stadio) è una pagina di esempio, ma è lo stesso per ogni squadra.

# Punto di contatto

redazione@tuttocampo.it - sul sito è indicato di scrivere qui per segnalazioni di utilizzo di materiale improprio

**Comment by LorenzoStucchi** [comment]
Risposta:

> ci scusiamo, non avevamo visto la mail precedente. Interveniamo a breve e vi facciamo sapere appena la modifica è fatta, se riusciamo anche in giornata.

**Comment by LorenzoStucchi** [comment]
Inviato un sollecito

/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
Inviata nuova segnalazione 

/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
Risposta:

> ci scusiamo per il ritardo. Avevamo preso in mano gli sviluppi ma poi si erano interrotti per dei problemi tecnici.
> Riprendiamo in mano il tutto e vi facciamo sapere.
> 
> Ci scusiamo ancora,
> Tuttocampo.it

**Comment by LorenzoStucchi** [comment]
Inviato nuovo sollecito

/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
Inviata nuova richieste

**Comment by LorenzoStucchi** [comment]
Risposta:

> abbiamo finalmente aggiornato la mappa. È tutto ok ora?
> Grazie e ci scusiamo per il ritardo

Riporta ad ora l'attribuzione corretta

![immagine](https://user-images.githubusercontent.com/29042221/206669339-46ebf76f-c75d-40dc-a58f-8bcc1f6532ba.png)
