### ISSUE TITLE
Mancata attribuzione a OSM - Legambiente Trino

### ISSUE THREAD

**Issue by musuruan** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#57]
# Descrizione

In un video pubblicato su YouTube compaiono diverse mappe prese da OSM senza alcuna attribuzione.

## Riferimento del prodotto senza attibuzione

https://www.youtube.com/watch?v=qbNloVg-lAA

# Punto di contatto

legambientetrino@gmail.com

**Comment by LorenzoStucchi** [comment]
Risposta:

> scusandoci per l'increscioso 'incidente", vi segnaliamo che abbiamo provveduto ad inserire l'etichetta 
>  "©OpenStreetMap contributors”, utilizzando la relativa opzione nel tool utilizzato per la creazione dei video: per vostra informazione il tool Magix.
> Abbiamo rimosso il vecchio video e pubblicato quello nuovo. 
> Lo trovate al seguente link:  
> https://youtu.be/BX1QWE7LGNU
> Sperando che questo rispetti le regole di pubblicazione dei contenuti creati grazie al supporto delle vostre mappe, vi porgiamo i nostri più cordiali saluti,
> Legambiente Gruppo Trino

Come segnala @musuruan ora il video ha i riferimenti corretti
