### ISSUE TITLE
Mancata attribuzione a OSM - coobiz.it

### ISSUE THREAD

**Issue by lucamp** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#59]
# Descrizione

Cercando un azienda nel sito coobiz.it, la mappa OSM nella scheda mostra solo "Leaflet", senza specificare nulla a OpenStreetMap. Inoltre è scritto decisamente troppo in piccolo

## Riferimento del prodotto senza attibuzione

https://www.coobiz.it/azienda/pieve-di-soligo-gestione-reti/co8146223

ed ogni altra azienda presente nel sito

# Punto di contatto

info@coobiz.it
https://www.coobiz.it/contattaci

**Comment by LorenzoStucchi** [comment]
Inviata segnalazione tramite mail

/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
Risposta:

> come richiesto abbiamo inserito "©OpenStreetMap contributors" nella parte bassa delle mappe.

L'attribuzione ora è corretta
