### ISSUE TITLE
Mancata attribuzione a OSM - visitamontesilvano.it

### ISSUE THREAD

**Issue by pippopip** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#6]
# Descrizione
In homepage c'è OSM senza attribuzione. POI markers sono sovrapposti alla cartina, ma i POI non sembrano essere presi dal database, da qualche verifica a campione.

Secondo gli articoli di giornale [1](https://www.ilpescara.it/cronaca/montesilvano/mappa-digitale-attivita-commerciali.html) [2](https://www.ilcentro.it/pescara/bar-ristoranti-e-negozi-arriva-la-mappa-per-turisti-1.2639353), la mappa era cartacea negli anni scorsi, ma non non so se fosse derivata da OSM e non ne ho una copia.

## Riferimento del prodotto senza attibuzione
https://www.visitamontesilvano.it/

# Punto di contatto
Non trovo le email di autori e committenti su questo sito.

- autore: `Web Design Lorenzo Agency & Initaly` secondo il pie' di pagina della homepage
  - cercare `Initaly Pescara` dà [un sito](https://www.webagencyinitaly.com/about-video/) che in basso dice `info@webagencyinitaly.com`
  - cercare `Lorenzo Agency Pescara` dà [Facebook](https://www.facebook.com/lorenzoagency/)
- committenti:
  - `Associazione Commercianti Montesilvano nel Cuore` ha [Facebook](https://it-it.facebook.com/Associazione-Commercianti-Montesilvano-nel-Cuore-210438135746720/about/) e ha un numero whatsapp indicato [qui](https://www.visitamontesilvano.it/add-listing/) (`Per completare la scheda inviateci...`)
  - `Confesercenti Pescara` [sito web](http://www.confesercentipe.it/)  e-mail: info@confesercentipe.it
- Google trova pagine del sito in violazione che non riesco a raggiungere dalla homepage, pertanto non so se sono pagine di test con info fasulle non destinate al pubblico.
  - [lorenzo agency](https://www.visitamontesilvano.it/directory/lorenzo-agency-2/) dà whatsapp e un sito web che non esiste, pertanto l'email potrebbe non funzionare, avendo lo stesso dominio
  - [montesilvano nel cuore](https://www.visitamontesilvano.it/author-profile-2/wp_11632668/) dà `assmontesilvanonelcuore@gmail.com` che google non riesce a trovare altrove su internet
- Patrocinio del Comune di Montesilvano:
  - Assessore al turismo di Pescara: Deborah Comardi assessore.comardi@comune.montesilvano.pe.it [fonte](https://www.comune.montesilvano.pe.it/organi-e-struttura/giunta/)
  - Assessore al commercio di Pescara: Paolo Di Blasio assessore.diblasio@comune.montesilvano.pe.it [fonte](https://www.comune.montesilvano.pe.it/organi-e-struttura/giunta/)

**Comment by LorenzoStucchi** [comment]
Grazie per la descrizione molto dettagliata e i numerosi riferimenti e contatti. Ho inviato la mail all'associazione, al sindaco e a confesercenti. Mi sembrava eccessivo aggiungere anche gli assessori. Lo sviluppatore verrà nel caso contattato da loro

**Comment by pippopip** [comment]
Grazie mille. Ho fede nel vs miglior giudizio nella scelta del destinatario e della via di contatto: ho dettagliato le fonti per aggirare la condizione che `Il contatto deve essere presente nel sito web` esplicitata nel template di nuova issue, ma, ripensandoci, forse è intesa soltanto ad evitare omonimie

**Comment by LorenzoStucchi** [comment]
Grazie, il senso della condizione è di condividere indirizzi che sono pubblici

**Comment by LorenzoStucchi** [comment]
Risposta:

> nel ringraziarla per la segnalazione, le comunichiamo che stiamo provvedendo alle dovute modifiche.
> Nel caso dovesse riscontrare altre anomalie non esiti a contattarci nuovamente al fine di provvedere ulteriormente.

**Comment by LorenzoStucchi** [comment]
Risposta:

> Le comunichiamo che le variazioni sono state effettuate come si evince dallo screen allegato.
> Per qualsiasi altra necessità resto a disposizione.

La correzzione è solo parziale e non è chiaro a cosa si riferisca il testo inserito. Invio indicazione su come fare l'attribuzione con leaflet  https://leafletjs.com/examples/quick-start/#setting-up-the-map

<img width="1277" alt="Schermata 2021-07-14 alle 09 40 10" src="https://user-images.githubusercontent.com/29042221/125582778-565714d9-4ae9-4f0b-8118-21c1f240c99e.png">

**Comment by LorenzoStucchi** [comment]
L'attribuzione è stata riportata non nella forma suggerita ma credo che il riferimento sia chiaro. 

Cosa ne pensi @pippopip ?

**Comment by pippopip** [comment]
Grazie mille per il lavoro che fai! Almeno hanno messo il nome e il link.

Il senso dell'attribuzione e [la richiesta esplicita nella licenza](https://wiki.openstreetmap.org/wiki/Community_attribution_advice#What_we_mean_by_attribution) è rendere impossibile che la mappa appaia senza che l'utente sia stato informato almeno una volta. Per fruire di questa mappa è necessario che l'attribuzione non appaia, perché la spaziatura rende l'attribuzione visibile soltanto se si scorre molto al di sotto della mappa, come l'amministrazione stessa potrebbe verificare su qualunque schermo di un comune laptop grande o piccolo.

L'attribuzione è difficile da notare, per il colore grigio chiaro su sfondo bianco, a differenza dello screenshot di luglio: il colore del carattere nel sorgente della pagina è RGB 122, 130, 166, quindi non è un problema di schermo.

Però non sono sicuro che insistere avrebbe effetto, a maggior ragione se mi sembra di capire che non abbiano risposto alla seconda e-mail con le istruzioni leaflet, perfino per chiedere un chiarimento. Non ho interesse personale in questo sito, che resta in violazione dopo ben due mesi.

**Comment by LorenzoStucchi** [comment]
Grazie @pippopip, corcordo che insistere non porterà a delle modifiche, inoltre hanno evidentente modificato il sito per ridurre la visibilità.

Rimarraà un'attribuzione parziale ma ora almeno è presente un riferimento

**Comment by pippopip** [comment]
Certo, adesso l'utente ha il necessario per farsi un'idea e trarre le proprie conclusioni.
