### ISSUE TITLE
Mancata attribuzione a OSM - tabUi

### ISSUE THREAD

**Issue by fansanelli** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#60]
# Descrizione

App di promozione del territorio e delle big bench. In questo momento viene mostrata la mappa OSM, senza attribuzione, quando di sceglie "espandi mappa" da un POI, oppure "mappa" nella tab esplora.

## Riferimento del prodotto senza attibuzione

Esempio di come si visualizza la mappa da app: 
https://www.instagram.com/p/CdF48u4NGVX/

# Punto di contatto

info@tabui.app "Tapp s.r.l."

Grazie mille
Francesco

**Comment by LorenzoStucchi** [comment]
Risposta:

> la ringrazio per la sua segnalazione.
> Si assolutamente prendiamo in carico e modifichiamo come indicato.
> Mi scuso per non averlo fatto prima, ma lo sistemiamo.
> Qualora avessimo necessità ci premuriamo di contattarla nuovamente
> grazie
> PS: è possibile conoscere tutte le funzionalità nelllo specifico? API per poter sfruttare al meglio le vostre infinite caratteristiche?
> Grazie e buon lavoro

**Comment by LorenzoStucchi** [comment]
Risposta: 

> abbiamo pronta una nuova versione con i credits di OpenStreetMap che ci ha indicato. Saranno all’interno del riquadro della mappa, in basso a destra, con il link alla pagina dedicata (https://www.openstreetmap.org/copyright). Nell’attesa dell’approvazione della nuova release da parte degli store, le lascio in allegato uno screenshot di anteprima di come verrà visualizzata.

@fansanelli riesci a verificare su c'è l'attribuzione

<img width="392" alt="screenshot openstreet" src="https://user-images.githubusercontent.com/29042221/167842096-805c8a1d-dad8-4f16-aa4f-e0be57f2edd7.png">

**Comment by fansanelli** [comment]
> Risposta:
> 
> > abbiamo pronta una nuova versione con i credits di OpenStreetMap che ci ha indicato. Saranno all’interno del riquadro della mappa, in basso a destra, con il link alla pagina dedicata (https://www.openstreetmap.org/copyright). Nell’attesa dell’approvazione della nuova release da parte degli store, le lascio in allegato uno screenshot di anteprima di come verrà visualizzata.
> 
> @fansanelli riesci a verificare su c'è l'attribuzione
> 
> <img alt="screenshot openstreet" width="392" src="https://user-images.githubusercontent.com/29042221/167842096-805c8a1d-dad8-4f16-aa4f-e0be57f2edd7.png">

Grazie molte per la celere risposta e i risultati ottenuti! Al momento non è ancora proposto l'aggiornamento, ma chiuderò il ticket appena l'app si aggiorna.
Grazie ancora

**Comment by fansanelli** [comment]
Confermo che ora la mappa si visualizza come da immagine allegata.
Grazie e buon lavoro
Francesco
