### ISSUE TITLE
Mancata attribuzione a OSM - terredipisa.it

### ISSUE THREAD

**Issue by andrea-del-sarto** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#61]
# Descrizione
Attribuzione mancante, si limitano ad un generico [Leaflet | TerrediPisa.it © 2020]; sia nella mappa in home, sia nelle mappe delle singole attrazioni

## Riferimento del prodotto senza attibuzione
- mappa in home > https://www.terredipisa.it/#mapid
- mappa attrazione > https://www.terredipisa.it/attrazione/musei-villa-baciocchi-capannoli/#mapid

# Punto di contatto
per i contatti ho trovato questi, spero siano quelli giusti:
- promozione@pi.camcom.it
- cameracommercio@pi.legalmail.camcom.it

**Comment by LorenzoStucchi** [comment]
Risposta:

> La informiamo di avere contattato il referente tecnico del sito
> Attendiamo un riscontro e le faremo sapere

**Comment by LorenzoStucchi** [comment]
Risposta:
> il nostro fornitore ci ha informato di avere inserito l’indicazione in tutte le mappe. 
> Se doveste trovare altre mappe mancanti dell'indicazione del Copyright si invita a segnalarci la/e pagina/e

La mappa è stata correttamente attribuita

![immagine](https://user-images.githubusercontent.com/29042221/173069107-a1127f37-945e-4751-8f2c-d3b002d8cda9.png)
