### ISSUE TITLE
Mancata attribuzione a OSM - Milano Cortina 2026

### ISSUE THREAD

**Issue by Tresho** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#62]
# Descrizione
Il sito ufficiale della fondazione Milano Cortina 2026 utilizza mappa Mapbox per mostrare le città dove si trovano gli impianti, senza attribuzione in basso a destra. Lo stesso si verifica nelle pagine delle singole città che riportano un maggiore dettaglio della posizione dei singoli impianti.
Analizzando il codice HTML della pagina si nota che l'attribuzione ci sarebbe ma è in qualche modo disabilitata/coperta.

## Riferimento del prodotto senza attibuzione
[I luoghi](https://www.milanocortina2026.org/it/i-luoghi/)
[Esempio singola città - Cortina](https://www.milanocortina2026.org/it/i-luoghi/cortina-d-ampezzo/)

# Punto di contatto
info@milanocortina2026.org - Da pagina contatti
affarilegali@fondazionemilanocortina2026.org - Da note legali, dove è specificato:

> Gli utenti che abbiano individuato un qualsivoglia Contenuto Utente che ritengono illecito, inappropriato, offensivo o volgare sono invitati a segnalarlo tempestivamente a Fondazione utilizzando la casella affarilegali@fondazionemilanocortina2026.org. L'utente è invitato a un uso responsabile delle proprie segnalazioni. Le segnalazioni che dovessero rivelarsi infondate e/o illegittime saranno fonte di responsabilità a Suo carico.

**Comment by LorenzoStucchi** [comment]
La mail affarilegali@fondazionemilanocortina2026.org non esiste. Vediamo se rispondono dall'altra

> Non è stato possibile recapitare il messaggio. Il record DNS (Domain Name System) ha segnalato che il dominio del destinatario non esiste.
> 
> Contatta il destinatario in altro modo (ad esempio tramite telefono) e chiedi di avvertire l'amministratore della posta elettronica che sembra che il loro dominio non sia registrato correttamente presso il registrar. Specifica i dettagli dell'errore elencati di seguito. È probabile che l'amministratore della posta elettronica del destinatario sia l'unica persona in grado di correggere il problema.

**Comment by LorenzoStucchi** [comment]
Risposta automatica:

> Grazie per averci contattato. 
> La nostra organizzazione è attualmente costituita da un piccolo gruppo di persone, ma stiamo raccogliendo suggerimenti e richieste di informazioni e contiamo di fornirti una risposta nel più breve tempo possibile.
> Ti invitiamo anche a consultare la sezione FAQ sul sito di Milano Cortina 2026 per scoprire le nostre risposte alle domande più frequenti.
> Saluti Olimpici

Forse la scorsa volta l'errore dell'altro account non aveva fatto arrivare la mail

**Comment by LorenzoStucchi** [comment]
Risposta:

> le confermiamo di aver preso in carico la sua segnalazione e le comunichiamo che è ancora in corso l’istruttoria necessaria a darle un adeguato riscontro, tuttavia le confermiamo sin d’ora che saranno senz’altro posti in essere tutti gli adeguamenti del sito web di Milano Cortina 2026 che risulteranno necessari all’esito di tale esame.
> Le faremo saper quanto prima.

**Comment by LorenzoStucchi** [comment]
Mappa correttamente attribuita tramite attribuzione di Mapbox

![Schermata 2022-10-02 alle 10 58 49](https://user-images.githubusercontent.com/29042221/193446429-9e8d087a-d0a3-4031-9843-44f5ed6ad352.png)
