### ISSUE TITLE
Mancata attribuzione IlPost

### ISSUE THREAD

**Issue by czanongit** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#63]
Nell'articolo al link della testata Il Post, si vede una cartina con l'aspetto classico di OSM Mapnic, ma non si vede alcuna indicazione della fonte della mappa. Suppongo crop "veloce". 
https://www.ilpost.it/2022/06/09/terremoto-marche-abruzzo

**Comment by LorenzoStucchi** [comment]
Ciao @czanongit 
La mappa è stata tagliata ma a seguito della segnalazione #48 hanno imparato la lezione e hanno messo un attribuzione parziale in fondo alla pagina
