### ISSUE TITLE
Mancata attribuzione a OSM - TED Tuscia Esplorazione Divulgazione

### ISSUE THREAD

**Issue by DinoM65** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#64]
# Descrizione
L'associazione "**TED Tuscia Esplorazione Divulgazione**" insieme all’associazione “**Amici della Via Clodia APS**” hanno utilizzato il data base di OSM per realizzare cartografie (analogica e digitale) dei territori dei comuni di Oriolo Romano, Vejano, Blera, Barbarano Romano, Vetralla. Tale cartografia viene anche utilizzata in quattro pannelli collocati lungo alcuni percorsi escursionistici riportando i dati di siti archeologici e i sentieri più importanti come la Via Francigena e la Via Clodia da me mappati, molti dei quali l'associazione “Amici della Via Clodia APS” non era a conoscenza (la data del il mio post su OSM [Antica Via Clodia](https://www.openstreetmap.org/user/Dino%20Michelini/diary/398924) è prima delle integrazioni fatte da Aminici della Via Clodia APS). Poiché in ballo ci sono cospicui finanziamenti da parte della Regione Lazio che interessano all“**Amici della Via Clodia APS**, associazione di cui non si ha notizia dell'esistenza di organi sociali, che cerca di farsi accreditare come attore ed attuatore della realizzazione di un percorso atorico-escursionistico senza proporre un tracciato verosimile a quello dell'antica strada consolare, di questa situazione è anche a conoscenza anche il Sindaco di Oriolo Romano con il quale ho avuto uno scambio di e-mail in cui rappresentavo che il percorso individuato dalla non è la Via Clodia. Inoltre, nei post pubblicati nelle rispettive pagine Facebook scrivono: "recentemente, sono stati aggiunti circa una trentina di nuovi punti d'interesse, proprio nelle zone di Oriolo Romano, Bassano Romano e Vejano. Tutto questo, grazie alla proficua collaborazione che è nata con il gruppo “Amici della Via Clodia”, in particolare nella persona del Sig. Paolo Guardala"; i punti segnalati e caricati in questione sono derivati dai dati OSM che il Sig. Paolo Guardala (che purtroppo conosco bene...) ha copiato e caricato sulla pagina https://www.tedwebgis.altervista.org/.
L'attribuzione e l'uso dei dati OSM è completamente mancante; tale mancanza dovrebbe essere corretta riportando nei post https://www.facebook.com/ArcheoGeoBio/posts/495843352293032?__tn__=-R  una nota che spieghi da dove ha origine la base dati geografica, la corretta attribuzione dei dati a OSM e, soprattutto, come questi dati possono essere scaricati gratuitamente ed utilizzati su smartphone e GPS, come sono riuscito a fare anni fa nel sito ufficiale del Comune di Oriolo Romano [Sentieristica-Informazioni di carattere generale](https://comune.orioloromano.vt.it/contenuti/303734/informazioni-carattere-generale), di modo da chiarie la fonte dei dati e in particolare consentire alle persone di disporre su smartphone e GPS di una cartografia gratuita, aggiornata e verificata senza dover rivolgersi a soggetti quali  CAI Viterbo, TED e Amici della Via Clodia APS che gestiscono tali informazioni in modo del tutto scorretto e a loro esclusivo vantaggio ad es. vendendo cartografia cartacea, offrendosi come guide ed organizzando escursioni e trekking a pagamento.
Inoltre, anche la cartografia utilizzata nei quattro pannelli dovrebbe riportare la corretta attribuzione dei dati a OSM, sia per la parte di base dati che per i punti archeologici riportati.

## Riferimento del prodotto senza attibuzione
url mappa web : https://www.facebook.com/Amiciviaclodia/posts/753282736020796?__tn__=-R
url mappa web : https://www.tedwebgis.altervista.org/.
oltre a 4 pannelli installati lungo sentieri territori di Oriolo Romano, Vetralla, Blera...

# Punto di contatto
maupr76@gmail.com, Mauro Profeta, gestore pagine facebook TED
info@amiciviaclodia.com, Paolo Guardala, proprietario agriturismo "la castellina15"

**Comment by LorenzoStucchi** [comment]
Ciao @DinoM65 

Le mail indicate sono disponibili online? sai darmi un riferimento a dove le hai trovate?

**Comment by DinoM65** [comment]
Si sono disponibili online
[maupr76@gmail.com](mailto:maupr76@gmail.com), Mauro Profeta, gestore pagine facebook TED vedi https://www.facebook.com/ArcheoGeoBio/about;
[info@amiciviaclodia.com](mailto:info@amiciviaclodia.com), Paolo Guardalà, proprietario agriturismo "la castellina15" deriva da https://www.facebook.com/Amiciviaclodia/ quindi https://www.amiciviaclodia.com/ per finire a https://www.lacastellina15.com/ (tutti gestiti da Paolo Guardalà)

**Comment by LorenzoStucchi** [comment]
Risposta:

> sono Gabriele Trevi e le scrivo a riguardo della sua mail, arrivata qualche giorno fa al mio collega, sul fatto che sul portale https://www.tedwebgis.altervista.org/ non sono state inserite le licenze di OpenStreetMap.
> 
> Per prima cosa le chiedo scusa per questa mia dimenticanza, non era mia intenzione mancare di rispetto alla community di OpenStreetMap (la quale stimo moltissimo) e sicuramente non era mia intenzione prendere meriti che non mi spettano.
> 
> Come sicuramente ha potuto vedere il sito che sono riuscito a costruire non ha nessuno fine di lucro e soprattutto è una piattaforma open; quindi di per sé nasce con la stessa linea di pensiero di OpenStreetMap.
> 
> La mancanza della scritta delle licenze fondamentalmente è nata dal fatto che io non sono molto capace ad utilizzare il linguaggio di programmazione e per elaborare il sito mi sono fatto aiutare da un amico (molto più pratico di me) e nei giorni che abbiamo lavorato per attivare il geoportale fondamentalmente ci siamo scordati di inserire questa unico e fondamentale requisito: ovvero inserire la licenza sulla mappa.
> 
> Chiedo ancora scusa per questa mia personale incuranza e se è possibile vorrei chiedere come potrei fare per inserire la licenza sul portale così da non essere più in difetto con i requisiti richiesti.
> 
> Se a piacere parlare con le lascio il mio contatto telefonico, così da poter parlare e spiegare nel migliore dei modi questa situazione davvero molto spiacevole. 
> 
> La ringrazio per l'attenzione, spero abbia la pazienza di rispondermi.

**Comment by LorenzoStucchi** [comment]
Risposta:

> Buonasera Lorenzo e scusi il disturbo.
> 
> Credo di aver risolto, per qualsiasi cosa mi contatti pure.
> 
> Grazie mille per la pazienza e buona serata
