### ISSUE TITLE
Mancata attribuzione a OSM - straginazifasciste.it

### ISSUE THREAD

**Issue by Jrachi-2** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#65]
# Descrizione

Sulle pagine dei luoghi delle stragi sono presenti mappe Openstreetmap senza alcuna attribuzione.
Anche nella pagina dei crediti non esiste alcun riconoscimento

## Riferimento del prodotto senza attibuzione

http://www.straginazifasciste.it/?page_id=38&id_strage=975

# Punto di contatto
atlantestragi@insmli.it
Il sito web è stato progettato e realizzato da Toni Rovatti e Igor Pizzirusso.

**Comment by LorenzoStucchi** [comment]
Nel banner è comunque presente una parziale attribuzione 

![immagine](https://user-images.githubusercontent.com/29042221/177861989-b0f48c5e-7913-456f-8cb6-ac1484320fbd.png)

/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
Risposta:

> come già comunicato in altra mail, il credito è presente in ogni pagina del sito, anche se non sotto alle mappe, bensì in calce.
> Cercheremo comunque di aggiungerlo anche nelle mappe (ed è strano che non vi sia di default, visto che usiamo le vostre API).
