### ISSUE TITLE
Mancata attribuzione a OSM - distanzechilometriche.net

### ISSUE THREAD

**Issue by DinoM65** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#67]
# Descrizione
il sito è un motore di routing che utilizza mappe OpenStreetMap senza alcuna attribuzione.
Anche nella pagina dei crediti non esiste alcun riconoscimento.

## Riferimento del prodotto senza attibuzione
[url mappe OSM](https://distanzechilometriche.net/stradario/)
https://distanzechilometriche.net/stradario/

# Punto di contatto
michelin@distanzechilometriche.net - Michelin Blanchard

**Comment by LorenzoStucchi** [comment]
Mappa correttamente attribuita

![Schermata 2022-10-02 alle 11 07 42](https://user-images.githubusercontent.com/29042221/193446732-89781448-9988-42d8-bfa2-f7d873a7e344.png)
