### ISSUE TITLE
Mancata attribuzione a OSM - Club Alpino Italiano sezione Viterbo

### ISSUE THREAD

**Issue by DinoM65** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#68]
# Descrizione
Le mappe pubblicate dalla sezione CAI di Viterbo sul sito internet [CAI Viterbo](http://www.caiviterbo.it/) link menu [Sentieri](http://www.caiviterbo.it/sentieri.html) riportano in file pdf chiamati “**Carta dei sentieri**” mappe OpenStreetMap senza alcuna attribuzione; si tratta di file pdf con immagine di carta topografica di dati OSM gestita con il software [Land](https://www.twonav.com/it/software/land) (versione inferiore alla 8) della TwoNav ed impaginata con un word processor.

_Impostazioni preferenze Land (File->Preferenze)_
- Rilievi: disegna rilievi con ombreggiatura “Luce dall’alto”;
- Griglie: mostra “on”; colore “nero”; intervallo “1 Km”;
- Tracce: disegna frecce sopra la traccia “off”; disegna ombreggiatura delle tracce “off”;
- Unità: coordinate “UTM”; unità “m”; datum visualizzazione “WGS84”; datum interno “WGS84”.

_Mappe utilizzate in Land (archivi on-line->world):_
- OpenStreetMap_Topo.cosm
- World_Base_Relief.cwdem

_Processo di creazione_
In Land caricata la traccia gpx e le mappe sopra richiamate, si creano due file immagine: una prima immagine relativa alla traccia gpx e alle due mappe visualizzate a video; una seconda immagine relativa al grafo dell’elevazione della traccia gpx. Successivamente, tramite un word processor ed un file con layout opportunamente predisposto di testatina customizzata (loghi, nome percorso, riferimento geografici, scala) si inseriscono le immagini prodotte precedentemente. Quindi si personalizza il layout inserendo varie icone, bandierine CAI e testi a corredo della mappa.

_Possibili azioni risolutive_
Rimuovere tutti i riferimenti a mappe OSM comprewi i link e file pdf “Carta dei sentieri” ed ogni altra informazione geografica OSM contenuta in file immagine, mappe, ecc. dove non venga correttamente citata l’attribuzione a OSM.

Oppure, in alternativa:
- inserire nella pagina “Sentieri” del sito CAI VT un link (o paragrafo nella pagina Sentieri) che spieghi:
1. da dove ha origine la base dati geografica;
2. la corretta attribuzione dei dati a OSM (di modo da chiarire la fonte dei dati;
3. come i dati OSM possono essere scaricati gratuitamente ed utilizzati su smartphone e dispositivo GPS consentendo alle persone un uso consapevole dei dati geografici OSM e disporre su smartphone e dispositivo GPS di una cartografia gratuita, aggiornata e verificata;
- inserire in ogni file pdf “Carta dei sentieri” e in goni mappe OSM pubblicata sul sito CAI VT l’attribuzione ad OSM.
## Riferimento del prodotto senza attibuzione
Nella pagina [Sentieri](http://www.caiviterbo.it/sentieri.html) sono riportati link “**Carta dei sentieri**” di file pdf con le mappe.
# Punto di contatto
[presidente.caiviterbo@gmail.com](mailto:presidente.caiviterbo@gmail.com) - Stefania Di Blasi (presidente sezione CAI Viterbo)

**Comment by LorenzoStucchi** [comment]
@DinoM65 le mappe continuano ad usare OpenStreetMap?

**Comment by DinoM65** [comment]
Ho controllato ora e ancora vi sono PDF scarocabili con OMS

**Comment by LorenzoStucchi** [comment]
Nuovo contatto alessandro.selbmann @ gmail.com

**Comment by LorenzoStucchi** [comment]
Risposta:

> se ho ben capito, debbo aggiungere alle cartine, in angolo in basso, una delle 2 stringhe indicate nella mail.
> Comincio a lavorarci: ci vorrà un pò di tempo.
> Grazie per tutto quello che fate: anche noi siamo volontari ed operiamo con passione per la collettività.
> Cordiali saluti.

**Comment by LorenzoStucchi** [comment]
Risposta a richiesta tempistiche:

> Stiamo provvedendo.
> Ci vorrà solo un po ti tempo.

**Comment by LorenzoStucchi** [comment]
Le attribuzioni risultano ora presenti nella mappe controllate

@DinoM65 confermi?
