### ISSUE TITLE
Mancata attribuzione a OSM - Associazione Turistica Brunico Kronplatz Turismo

### ISSUE THREAD

**Issue by guerda** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#69]
# Descrizione
slippy map on bruneck.com. Example:  https://www.bruneck.com/de/infos/restaurant-kron_4573

## Riferimento del prodotto senza attibuzione

![Screenshot_20220712-151806.png](https://user-images.githubusercontent.com/230782/178499866-109c6f70-7128-4526-87ea-335b089ee5b1.png)

# Punto di contatto

info@bruneck.com

https://www.bruneck.com/de/planen-buchen/kontakt

**Comment by LorenzoStucchi** [comment]
Usata la mappa https://www.bruneck.com/it/info/museo-mansio-sebatum-a-san-lorenzo-_2689#map_1

/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
Nessuna risposta alla mail, test contatto con pagina facebook dell'associazione

**Comment by LorenzoStucchi** [comment]
Risposta su facebook, ma niente è cambiato

> Ciao, sì è corretto 👍 l’abbiamo sicuramente ricevuta e già inoltrata alla persona responsabile.

**Comment by LorenzoStucchi** [comment]
Attribuzione corretta

![immagine](https://user-images.githubusercontent.com/29042221/212619061-15732a5e-3eb4-46e7-919f-022d0fc42245.png)

**Comment by guerda** [comment]
Thank you for your persistence!
