### ISSUE TITLE
Mancata attribuzione a OSM - Bricoman

### ISSUE THREAD

**Issue by ricloy** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#7]
# Descrizione

Sul sito di una catena di negozi di bricolage francese (Bricoman) viene utilizzata una mappa basata su OpenStreetMap per mostrare i negozi sul suolo italiano. Non sembra esserci alcuna attribuzione (neanche nascosta nelle voci copyright/Legale/etc). Manca anche un riferimento alla libreria usata (Leaflet). Sul sito francese (https://www.bricoman.fr/nos-magasins.html) viene usato Google.

## Riferimento del prodotto senza attribuzione

https://www.bricoman.it/it/stores/

# Punto di contatto

Sul sito sono riuscito a trovare solo un link a un form da compilare per contattare l'assistenza: https://bricoman.service-now.com/dvt_csp?id=dvt_create_case

Cercando su inipec.gov.it si trova l'indirizzo PEC dell'azienda:  bricoman@pec.bricoman.it

**Comment by LorenzoStucchi** [comment]
Inviata segnalazione tramite form e tramite pec

**Comment by LorenzoStucchi** [comment]
RIsposta al form:

> Le confermiamo che abbiamo preso in carico la sua segnalazione. 
> Stiamo pianificando l'intervento richiesto che dato il periodo estivo non sarà immediato, ma ci occuperemo comunque di portarlo a termine.

**Comment by LorenzoStucchi** [comment]
Testo ultima Mail:

> Gentile Cliente,
> la informiamo che non avendo ricevuto riscontro alla nostra richiesta di informazioni, il ticket è stato chiuso.
> Qualora avesse bisogno di assistenza, la invitiamo ad aprire un nuovo ticket.

Il problema non sembra essere stato risolto rispondo chiedendo chiarimenti

**Comment by LorenzoStucchi** [comment]
Avendo il ticket prodotto un risultato ho inviato una medesima segnalazione con un nuovo ticker

**Comment by LorenzoStucchi** [comment]
Risposta:
> ci dispiace per l'attesa.
> Il nostro servizio di mappa (consultabile a questa pagina: https://www.bricoman.it/it/stores/) è stato affidato ad un'altra piattaforma, pertanto non sarà più utilizzata la mappa di OpenStreetMap.
> La ringraziamo per averci contattato.

Pultroppo la mappa è stata cambiata ed ora utilizza Google Maps e non mi è possibile inviare un riscontro, peccato sarebbe bastato una piccola aggiunta, hanno evidentemente preferito seguire la versione del altro sito.
