### ISSUE TITLE
Mancata attribuzione a OSM - CAI Viterbo https://www.camminotuscia103.it

### ISSUE THREAD

**Issue by DinoM65** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#70]
# Descrizione

La sezione CAI di Viterbo ha recentemente pubblicato un sito deicato al percorso **CAI n. 103 [Cammino della Tuscia]( https://www.camminotuscia103.it)**. Nella home sono presenti mappe e link a mappe pdf che sono prive dell'attribuzione di OSM. La tecnica utilizzata per la cartografia in pdf è la medesima di quella già segnalata per il sito del CAI Viterbo pagina "**[Sentieri](http://www.caiviterbo.it/sentieri.html)**" link "**Carta sentieri**"
 
## Riferimento del prodotto senza attibuzione

https://www.camminotuscia103.it/
https://www.camminotuscia103.it/images/stories/carta-103.pdf

# Punto di contatto

presidente.caiviterbo@gmail.com - Stefania Di Blasi presidente CAI Viterbo

**Comment by LorenzoStucchi** [comment]
@DinoM65 pensi che la segnalazione sia ancora valida, sono state rimosse le mappe?

**Comment by DinoM65** [comment]
Da un controllo sulla home page c'è ancora una immagine di mappa con sfondo OSM ed un link "scarica la carta completa del cammino" con mappa avente sfondo OSM. Nessuna attribuzione a OSM.

**Comment by LorenzoStucchi** [comment]
Unita la segnalazione con l'altra issue essendo il riferimento lo stesso
