### ISSUE TITLE
Mancata attribuzione a OSM - il Post

### ISSUE THREAD

**Issue by Mannivu** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#71]
# Descrizione
In questo articolo https://www.ilpost.it/2022/08/05/beluga-senna-francia/ c'è una frazione di mappa chiaramente presa da OSM

## Riferimento del prodotto senza attribuzione
L'originale è in https://datawrapper.dwcdn.net/963vf/1/#?secret=3ER8GV4vft (dove si vede bene l'attribuzione in basso a destra)

# Punto di contatto
mail@ilpost.it da https://www.ilpost.it/chi-siamo/

**Comment by LorenzoStucchi** [comment]
Inviata segnalazione al direttore con il quale ci erano già stati contatti in precedenza per una mancata attribuzione

/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
L'errore sembra maggiormante riferito al tool Datawrapper che regola la grandezza della mappa alla sola larghezza della pagina, infatti da telefono l'attribuzione è presente. Ho inviato una segnalazione anche a Datawrapper

**Comment by LorenzoStucchi** [comment]
Dimensione dell'iframe nell'articolo corretta, l'attribuzione compare correttamente.

Gli sviluppatori di Datawrapper, dicono che non dipende da loro

![Schermata 2022-10-05 alle 22 09 16](https://user-images.githubusercontent.com/29042221/194153523-0e8331d3-e787-46c0-9bc6-9fa6a7628071.png)
