### ISSUE TITLE
Mancata attribuzione a OSM - Big Bench Community Project

### ISSUE THREAD

**Issue by musuruan** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#73]
# Descrizione

Sul sito web del Big Bench Community Project compaiono diverse mappe OSM senza attribuzione

## Riferimento del prodotto senza attibuzione

https://bigbenchcommunityproject.org/

# Punto di contatto

https://bigbenchcommunityproject.org/it/note-legali

**Comment by LorenzoStucchi** [comment]
Prova invio mail a creatore del sito info@zbservizi.net

/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
Risposta correzione:

> abbiamo sistemato l’attribuzione delle mappe sul sito di BigBenchCommunityProject che si trova in ogni riquadro di ogni mappa, posizionato in alto a sinistra. Potete vedere e provare il link direttamente sul sito ma lascio un’anteprima qui allegato alla mail.
> Restiamo a disposizione per qualsiasi cosa,
> buon lavoro e buona giornata

![Schermata 2022-10-31 alle 09 48 43](https://user-images.githubusercontent.com/29042221/199007663-395ab3be-968c-49a9-b074-6071930a0d2b.png)
