### ISSUE TITLE
Mancata attribuzione a OSM - apritimoda.it

### ISSUE THREAD

**Issue by e075e** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#77]
# Descrizione

Sito con mappa OSM ed attribuzione completamente mancante, appare solo "Leaflet"

## Riferimento del prodotto senza attribuzione

https://apritimoda.it/maison/museo-della-moda-e-delle-arti-applicate/
https://apritimoda.it/maison/armani/

Cliccare le frecce in alto a destra per cambiare "maison"

# Punto di contatto

https://apritimoda.it/scrivici/
MoD Milan open Doors & C. sas

**Comment by LorenzoStucchi** [comment]
Inviata altra segnalazioni a mail info e privacy

/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
Inviata ulteriore segnalazione alla mail, per ora nessuna risposta o modifica, valutare altri canali

/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
Nuova segnalazione tramite PEC 
/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
Risposta:

> Nel corso del trasferimento e del rifacimento del sito web [ApritiModa.it](http://apritimoda.it/), di proprietà di MoD, abbiamo trovato nelle caselle mail in via di migrazione questa vostro messaggio, di cui non eravamo a conoscenza, come mai ci erano stati segnalati vs. Messaggi in merito alla mancata attribuzione a Wikimedia di OpenStreetMap.
> Siamo molto spiacenti dell’accaduto: non ci saremmo mai permessi di non citarvi come richiesto e dovuto ma l’utilizzo di OpenStreetMap è stata una scelta del precedente fornitore che avrebbe dovuto attenersi alle condizioni d’uso, condizioni di cui non siamo mai stati consapevoli, avendo delegato la gestione del sito a fornitore terzo.
> Come sopra precisato, stiamo trasferendo e rifacendo il sito: attualmente il nuovo fornitore non ha ancora deciso se continuare ad utilizzare OpenStreetMap.
> Se così sarà, non mancheremo di contattarla e di procedere all’utilizzo corretto delle vostre mappe.
> Ci auguriamo di poter contare sulla vostra comprensione e riconoscimento della nostra buona fede.

**Comment by LorenzoStucchi** [comment]
Il sito è stato rifatto e le mappe rimosse
