### ISSUE TITLE
Mancata attribuzione a OSM - MoMap.it

### ISSUE THREAD

**Issue by lukescagn** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#78]
# Descrizione
Ho trovato questa azienda tra le pubblicità di Facebook. Il sito web riporta un'anteprima dell'applicazione con le mappe di OSM, ma senza attribuzione. Purtroppo non riesco a verificare che l'app effettivamente riporti l'attribuzione perché è necessario avere un account abilitato.

## Riferimento del prodotto senza attribuzione
https://www.momap.it/

# Punto di contatto
info@momap.it

**Comment by LorenzoStucchi** [comment]
Risposta:

> Sono Amato Pasquale responsabile del reparto informatico di MoMap, ho letto la sua email ma non trovo il riscontro sul nostro sito web [www.momap.it](http://www.momap.it/) in quanto l’unica mappa presente si trova presso questo link: https://www.momap.it/contact-5/ ed è Google. Potreste gentilmente girarmi il link  della mappa in questione?
 
Risposta successiva dopo aver segnalato la mancata attribuzione nell'applicazione:

> Perfetto, grazie della segnalazione provvederemo il prima possibile ad aggiungere l’attribuzione.

**Comment by lukescagn** [comment]
Ciao Lorenzo,
grazie per il tuo lavoro. Ho verificato che sul sito viene riportata ora la dicitura corretta "(C) OpenStreetMap contributors".
