### ISSUE TITLE
Mancata attribuzione a OSM - mountainbiker.it

### ISSUE THREAD

**Issue by luca-e075e** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#79]
# Descrizione

mappe web di percorsi ciclabili, nel riquadro attribuzione appare solo "Leaflet | Matzemann" ma le mappe usate sono basate su OSM

## Riferimento del prodotto senza attribuzione

https://mountainbiker.it/sexten/stoneman-trail.php
https://mountainbiker.it/wallis/gornergrad-europaweg.php
e altre mappe dei percorsi

# Punto di contatto

info@vinschgaubike.com - Vinschgaubike OHG Südtirol

**Comment by LorenzoStucchi** [comment]
Risposta:
