### ISSUE TITLE
Mancata attribuzione a OSM - geamap

### ISSUE THREAD

**Issue by lucadelu** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#8]
# Descrizione
Nel sito geamap lo stile IGM in realtà è quello di OSM e viene attribuito erroneamente ad IGM, inoltre ha uno stile chiamato OSM e in quel caso l'attribuzione è corretta 

## Riferimento del prodotto senza attibuzione
https://www.geamap.com/it/italia#zoom=11&lat=42.3768&lon=12.88&layer=13&overlays=FFFFFFFFFFFFFFFFFFFFFFF

# Punto di contatto
https://www.geamap.com/it/contact

**Comment by LorenzoStucchi** [comment]
Ciao @lucadelu la mappa di OSM è di deafult e le altre vengono caricate sopra. Il livello IGM non funziona e presenta un errore di sicurezza che non ne consente la visualizzazione (vedi immagine).
Conviene comunque mandare la segnalazione, ma con un messaggio diverso?

![Errore visualizzazione](https://user-images.githubusercontent.com/29042221/126752127-75f565ec-9072-48bf-aa06-dcb38b62a7b5.png)

**Comment by lucadelu** [comment]
@LorenzoStucchi io se apro https://www.geamap.com/it/italia mi appare OSM ma come attribuzione ho IGM, forse dovuto all'errore che hai segnalato però se OSM è di default l'attribuzione ci vorrebbe sempre

![Screenshot from 2021-07-23 10-17-54](https://user-images.githubusercontent.com/178741/126755712-96bc6be7-2daa-4c3b-8392-5443d99a9149.png)

**Comment by LorenzoStucchi** [comment]
@lucadelu si probabilmente hai nella cache la visualizzazione del layer dell'IGM, se mostri il layer di OSM come a questo link l'attribuzione è parzialemente corretta
 https://www.geamap.com/it/italia#zoom=7&lat=43.731&lon=13&layer=0&overlays=FFFFFFFFFFFFFFFFFFFFFFF

**Comment by lucadelu** [comment]
@LorenzoStucchi secondo me il layer dell'IGM è quello di default sopra a quello di OSM (ho provato diversi browser tutti in modalità incognito che non dovrebbe mantenere la cache se ricordo bene), non voglio insistere ma capire bene qual'è il problema. si confermo che se si seleziona il layer OSM l'attribuzione è corretta

**Comment by LorenzoStucchi** [comment]
@lucadelu si sembrerebbe così, ho provato anche io con un browser in incognito. Allora mando una segnalazione che la visualizzazione dei dati IGM non funziona e ciò non mostra in maniera chiara che il dato che invece viene visualizzato è la mappa di OSM.

**Comment by LorenzoStucchi** [comment]
Risposta:

> Buongiorno, grazie per l'osservazione.  In pochi giorni l'errore verrà corretto e la fonte OSM citata.  Saluti

**Comment by LorenzoStucchi** [comment]
È stata inserita l'attibuzione fissa ad OSM per ovviare all'errore indicato, vedi immagine.

![Schermata 2021-07-27 alle 09 26 08](https://user-images.githubusercontent.com/29042221/127113621-cb0e3371-8bf5-4115-9ade-c72a1c92469d.png)

**Comment by lucadelu** [comment]
Confermo che è stato aggiustato, chiudo
