### ISSUE TITLE
Mancata attribuzione a OSM - [Consorzio Vicenza è]

### ISSUE THREAD

**Issue by voschix** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#80]
# Descrizione

La brochure "VIbike", pubblicata e scaricabile come file PDF sul [sito del consorzio](https://www.vicenzae.org/index.php?option=com_content&view=article&id=651&Itemid=679&lang=en) 
utilizza mappe OSM, apparentemente senza attribuzione. Allego una pagina esempio.

https://resc.deskline.net/documents/1/TRN/ccdbadac-7f26-405b-a163-bf4a27a4c2c6/Libretto_ViBike.pdf

## Brochure VI Bike (in formato pdf) del "Consorzio Vicenza è"

# Punto di contatto

info@vicenzae.org; phone: +39 0444 99 47 70; fax: +39 0444 99 47 79

![VI Bike](https://user-images.githubusercontent.com/11076112/203072337-171be1ed-4214-48df-9c3e-225925686329.jpg)

**Comment by LorenzoStucchi** [comment]
RIsposta:

> La ringraziamo per quanto comunicatoci e ci scusiamo anticipatamente in quanto non eravamo a conoscenza dei requisiti per l’utilizzo delle mappe.
> Per sviluppare il nostro progetto Vi Bike ci siamo avvalsi di professionalità esterne al nostro Consorzio che nel trasmetterci i tracciati da pubblicare non ci hanno trasmesso indicazioni relative ai crediti.
> Il Pdf che si trova caricato nel nostro sito è relativo ad una pubblicazione cartacea realizzata per il progetto e che ad oggi risulta in fase di esaurimento.
> Procederemo sicuramente ad aggiornare il PDF e a ripubblicarlo corretto, così come faremo per la versione cartacea nel momento in cui dovessimo avere le risorse per poter stampare nuovamente.
> Al fine di procedere con l’aggiornamento del PDF inseriremo nella pagina in allegato la dicitura
>  
> Licenza per le mappe:  Open Data Commons Open Database License / OSM (ODbL/OSM) - Per ulteriori informazioni, vedi http://www.openstreetmap.org/copyright.
>  
> E’ corretta l’interpretazione che abbiamo dato?
> RingraziandoLa anticipatamente per l’attenzione e in attesa di un Suo cortese riscontro per poi procedere con le modifiche, colgo l’occasione per inviarLe i migliori saluti.

**Comment by LorenzoStucchi** [comment]
Alla fine del libretto sono state inseriti i riferimenti all'attribuzione ad OpenStreetMap


<img width="345" alt="Schermata 2022-12-19 alle 18 24 36" src="https://user-images.githubusercontent.com/29042221/208484182-fe80f61b-014c-423f-a2e0-a6ecdccc3aba.png">
