### ISSUE TITLE
Mancata attribuzione a OSM - Istituto Nazionale Ferruccio Parri

### ISSUE THREAD

**Issue by alesarrett** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#81]
# Descrizione
Il portale  https://www.luoghifascismo.it contiene delle mappe che usano come sfondo OpenStreetMap.
Mentre la mappa generale (https://www.luoghifascismo.it/mappa/) contiene correttamente l'attribuzione, quelle regionali (e.g. https://www.luoghifascismo.it/mappa/mappa-veneto/) e le schede di dettaglio (e.g. https://www.luoghifascismo.it/singolo-luogo-cercato/?ricerca=428) non la contengono.

## Riferimento del prodotto senza attribuzione
Un esempio delle mappe regionali: https://www.luoghifascismo.it/mappa/mappa-veneto/)
Un esempio delle schede di dettaglio: https://www.luoghifascismo.it/singolo-luogo-cercato/?ricerca=428

# Punto di contatto
Nel portale https://www.luoghifascismo.it non sembra esserci un contatto diretto.
Nel portale dell'ente responsabile della mappa, l'Istituto Ferruccio Parri (https://www.reteparri.it/contattaci/) è presente la seguente email di contatto: segreteria@insmli.it
Il referente del sito web è Igor Pizzirusso (https://www.luoghifascismo.it/crediti/)

**Comment by LorenzoStucchi** [comment]
Nuova segnalazione anche sulla mail di redazione
/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
Risposta:

> Grazie della segnalazione, ovvieremo prima possibile!

**Comment by LorenzoStucchi** [comment]
Risposta:

> dovremmo avere ovviato. Purtroppo temo che gli script siano vecchi e pertanto abbiamo riscontrato difficoltà con la classe ol-attribution,


![immagine](https://user-images.githubusercontent.com/29042221/213154737-106f53ae-b025-4ab8-89eb-035c0c20a8b8.png)
