### ISSUE TITLE
Mancata attribuzione a OSM - CAI Sentiero Italia

### ISSUE THREAD

**Issue by Tepepaz** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#82]
# Descrizione

La mappa web del Sentiero Italia CAI viene caricata su una webapp sviluppata dalla [3Liz](https://www.3liz.com/en/) che usa un layer della [Webmapp](https://webmapp.it/) sviluppato su dati OSM, ma senza attribuzione.

## Riferimento del prodotto senza attribuzione

[Sentiero Italia CAI 
](https://mappasentieroitalia.cai.it/)

# Punto di contatto
email: [infosentieroitalia@cai.it](mailto:infosentieroitalia@cai.it) 
pec: [cai@pec.cai.it](mailto:cai@pec.it)

**Comment by LorenzoStucchi** [comment]
Risposta:

> ci dispiace per l'accaduto. Come sicuramente saprai il CAI crede moltissimo nel progetto OpenStreetMap come confermato dalla rinnovata convenzione che abbiamo fatto da poco. Detto questo controlliamo quanto prima la tua segnalazione e vediamo di rimediare.

**Comment by LorenzoStucchi** [comment]
Corretta l'attribuzione

![immagine](https://user-images.githubusercontent.com/29042221/208615142-d8d643d5-23c8-463a-bae4-453ad78022da.png)
