### ISSUE TITLE
Mancata attribuzione a OSM - NL Newslinet.it

### ISSUE THREAD

**Issue by musuruan** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#83]
# Descrizione
Il seguente articolo pubblicato sul sito NL Newslinet.it mostra una mappa OSM senza alcuna attribuzione, presa dal sito https://lteitaly.it/it/ (dove però l'attribuzione è presente).

## Riferimento del prodotto senza attribuzione
https://www.newslinet.com/tv-dopo-refarming-banda-700-mhz-poco-o-nulla-utilizzata-dalle-telco-e-se-si-puntasse-al-dvb-i/

# Punto di contatto
https://www.newslinet.com/contattaci/

**Comment by LorenzoStucchi** [comment]
Risposta:

> Ha visto correttamente, ho utilizzato la mappa del sito lteitaly.
> In effetti la ho inserita staticamente (screenshot, non embeddata) in quanto mi piaceva quel certo particolare livello di zoom

![immagine](https://user-images.githubusercontent.com/29042221/206721399-8f5b39d1-0998-4c7e-99c0-a22597e9ef63.png)
