### ISSUE TITLE
Mancata attribuzione a OSM - FARMASI

### ISSUE THREAD

**Issue by canfe** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#86]
# Descrizione
La ditta FARMASI https://farmasi.it/ produce pannelli informativi per farmacie. Su questi pannelli è esposto l'elenco dinamico delle farmacie aperte con tanto di mappa. Le mappe usate sono quelle di OSM solo che in basso a destra l'attribuzione viene coperta dal loro logo 

## Riferimento del prodotto senza attribuzione
https://farmasi.it/bacheca-turni-farmacia/

# Punto di contatto
+39 030 3531970 [INFO@FARMASI.IT](mailto:info@farmasi.it)

PS: ho due foto fatte da me di questa bacheca con mappe della mia zona di cui son sicuro siano solo su OSM visti i particolari unici presenti.

**Comment by LorenzoStucchi** [comment]
@canfe riesci a caricare qui le mappe? Ho comunque inviato la segnazione

/remind me in 2 weeks

**Comment by canfe** [comment]
Eccole!

 

Da: Lorenzo Stucchi ***@***.*** 
Inviato: martedì 20 dicembre 2022 17:29
A: osmItalia/Segnalazioni-Mancata-attribuzione-OSM
Cc: canfe; Mention
Oggetto: Re: [osmItalia/Segnalazioni-Mancata-attribuzione-OSM] Mancata attribuzione a OSM - FARMASI (Issue #86)

 

@canfe <https://github.com/canfe>  riesci a caricare qui le mappe? Ho comunque inviato la segnazione

/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
@canfe serve caricarle su github, dalla mail non vengono incluse. Nel caso mandamele via mail e le carico io

**Comment by canfe** [comment]
![IMG_20221024_172559](https://user-images.githubusercontent.com/47743442/208873096-8efbc315-5ac0-415d-8387-0c9c16c74703.jpg)
![IMG_20221023_091236](https://user-images.githubusercontent.com/47743442/208873103-c7068204-4521-4090-bcea-2842385a19eb.jpg)

**Comment by LorenzoStucchi** [comment]
Risposta:

> riscontrata la Vostra in calce, con la presente, Vi comunichiamo che provvederemo nel più breve tempo possibile a sistemare le mappe da noi utilizzate.
> Rispettiamo molto il Vostro lavoro e ci scusiamo per la leggerezza dimostrata nell'utilizzo delle vostre proprietà intellettuali.
> Fermo restando quanto detto sopra Vi chiediamo cortesemente se sia possibile inserire anche il nostro logo in un angolo della mappa.
> In attesa di risconto porgiamo cordiali saluti e Vi auguriamo buone feste.

**Comment by LorenzoStucchi** [comment]
Risposta:

> noi abbiamo modificato in questa maniera. Può essere sufficiente?
> Sui nostri dispositivi invece è stata messa l'attribuzione direttamente sull'immagine mostrata. Come da file 1.png
> In attesa di vostre porgo cordiali saluti.

![1](https://user-images.githubusercontent.com/29042221/213668089-0f0ba0e8-f4fb-44ac-be91-68d3d72484a1.png)

@canfe resta da verificare che siano stati corretti e aggiornati realmente i dispositivi

**Comment by canfe** [comment]
Come si può vedere dall’immagine ad oggi nulla è cambiato.

 

Da: Lorenzo Stucchi ***@***.*** 
Inviato: venerdì 20 gennaio 2023 11:01
A: osmItalia/Segnalazioni-Mancata-attribuzione-OSM
Cc: canfe; Mention
Oggetto: Re: [osmItalia/Segnalazioni-Mancata-attribuzione-OSM] Mancata attribuzione a OSM - FARMASI (Issue #86)

 

Risposta:

noi abbiamo modificato in questa maniera. Può essere sufficiente?
Sui nostri dispositivi invece è stata messa l'attribuzione direttamente sull'immagine mostrata. Come da file 1.png
In attesa di vostre porgo cordiali saluti.

 <https://user-images.githubusercontent.com/29042221/213668089-0f0ba0e8-f4fb-44ac-be91-68d3d72484a1.png> 1

@canfe <https://github.com/canfe>  resta da verificare che siano stati corretti e aggiornati realmente i dispositivi

**Comment by LorenzoStucchi** [comment]
@canfe l'immagine allegata tramite mail non si vede, serve caricarla su github

**Comment by LorenzoStucchi** [comment]
Risposta sulle tempistiche:

> Abbiamo già fatto il 40%.
> Confido che per fine mese tutti i dispositivi saranno sistemati.

**Comment by canfe** [comment]
La farmacia per cui era partita la segnalazione è stata aggiornata! :-)
![IMG_20230304_124551](https://user-images.githubusercontent.com/47743442/222919447-67ace42b-5bd3-4eb0-bc6d-3bbda5e46c54.jpg)

**Comment by LorenzoStucchi** [comment]
Perfetto
