### ISSUE TITLE
Mancata attribuzione a OSM - Sardegna Sentieri

### ISSUE THREAD

**Issue by Tepepaz** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#87]
# Descrizione

Mappa interattiva degli itinerari accatastati in Sardegna e gestiti dall'ente foreste (Forestas)

## Riferimento del prodotto senza attribuzione

http://www.sardegnasentieri.it/mappa-interattiva

# Punto di contatto
[tavolo.tecnico.res@forestas.it](mailto:tavolo.tecnico.res@forestas.it) 
[protocollo.dg@pec.forestas.it](mailto:protocollo.dg@pec.forestas.it)
[ASABA@FORESTAS.IT](mailto:asaba@forestas.it) - Ing Alessio Saba RESPONSABILE UFFICIO SUB-DIRIGENZIALE
COORDINATORE TAVOLO TECNICO REGIONALE RETE ESCURSIONISTICA DELLA SARDEGNA (RES)
FUNZIONARIO TECNICO

**Comment by LorenzoStucchi** [comment]
Ricevuta risposta con intenzione di correzione nella versione finale del prodotto

**Comment by LorenzoStucchi** [comment]
Risposta:

> Buon pomeriggio Lorenzo,
> dovremmo aver risolto, grazie ancora per la cortesia e...a presto!

![immagine](https://user-images.githubusercontent.com/29042221/213781960-51fb7a88-2dc5-49db-875e-3b0261d097a7.png)

**Comment by ScottishLemur** [comment]
L'attribuzione non è stata corretta in tutto il sito e manca nelle schede presenti nella sezione "da vedere" https://www.sardegnasentieri.it/da-vedere

esempio:
https://www.sardegnasentieri.it/da-vedere/cala-luna
https://www.sardegnasentieri.it/da-vedere/foresta-bingionniga-jerzu
