### ISSUE TITLE
Mancata attribuzione a OSM - Autolinee Toscane

### ISSUE THREAD

**Issue by mfrasca** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#88]
# Descrizione
la cartina geografica sul sito delle Autolinee Toscane è realizzata utilizzando leaflet, prendendo i tasselli direttamente dal sito openstreetmap.org. manca del tutto l'attribuzione ad OSM.

## Riferimento del prodotto senza attribuzione
https://www.at-bus.it/it/biglietti-e-abbonamenti/punti-vendita/pisa

# Punto di contatto
all'indirizzo numeroverdetpl@regione.toscana.it ho mandato la seguente mail:

---

salve, vedo con piacere che utilizzate openstreetmap.org come mappa base del sito https://www.at-bus.it/it/biglietti-e-abbonamenti/punti-vendita/pisa

OSM è senza dubbio la migliore scelta per lo scopo, però avete tralasciato l'attribuzione della proprietà intellettuale, unica clausola per l'uso libero di OSM. da sito OSM:

> L'attribuzione da noi richiesta è "© OpenStreetMap contributors".
> Devi anche rendere evidente che i dati sono disponibili con licenza Open Database Licence. Ciò può essere ottenuto fornendo dei collegamenti con testo "Condizioni" o "Licenza" che puntano a [www.openstreetmap.org/copyright](http://www.openstreetmap.org/copyright) oppure [www.opendatacommons.org/licenses/odbl](http://www.opendatacommons.org/licenses/odbl).

vedo che utilizzate leaflet come cornice per includere la mappa. normalmente la configurazione di base di leaflet comprende l'attribuzione, sarà semplicissimo aggiungerla. se doveste avere bisogno di delucidazioni ulteriori, resto a vostra disposizione.

cordialmente, Mario Frasca.

**Comment by LorenzoStucchi** [comment]
Mi sembra di capire che una richiesta è già stata inviata. Il testo che utilizzo di solito per le richieste aperte tramite le issue qui è questo https://github.com/osmItalia/Segnalazioni-Mancata-attribuzione-OSM/blob/main/MAIL.md

**Comment by mfrasca** [comment]
spero non stia troppo male la versione che ho inviato. il passo successivo?

**Comment by mfrasca** [comment]
boh, non so se è poi tanto necessario insistere: sulla pagina in questione non c'è, ma quella per pianificare il viaggio https://www.at-bus.it/it/linee-e-orari/travel-planner sta tutta l'attribuzione completa pure di bandiera ucraina.

**Comment by LorenzoStucchi** [comment]
Essendo passato un po' di tempo e non hai ricevuto risposte, puoi provare ad inviare una mail con il formato di esempio che si usa di solito https://github.com/osmItalia/Segnalazioni-Mancata-attribuzione-OSM/blob/main/MAIL.md

**Comment by LorenzoStucchi** [comment]
Inviata nuova segnalazione tramite il form standard

/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
Riposte:

> Buongiorno Lorenzo, grazie infinite per la sua segnalazione abbiamo attivato le aree competenti perché si possa al più presto inserire i riferimenti da voi richiesti. Non appena saranno inseriti vi aggiornerò.
> Colgo anche l’ occasione di memorizzare il suo contatto se avremo bisogno di alcune delucidazioni riguardo ai dati che ci interessano importare sulla mappa.
> Grazie ancora e ci scusiamo per il disguido, non mancherò di aggiornarla non appena avremo implementato l’ attribuzione ad Open Street Maps

seconda risposta:

> Ciao Lorenzo,
> facciamo presente di aver inoltrato la tua segnalazione all'ufficio di competenza; il responsabile ha riferito che sarai a breve ricontattato.

**Comment by LorenzoStucchi** [comment]
Risposta:

> Buonasera Lorenzo, ho il piacere di comunicarti che abbiamo provveduto ad inserire il riferimento anche sulla mappa dei punti vendita
> https://www.at-bus.it/it/biglietti-e-abbonamenti/punti-vendita/grosseto
> Esempio su Grosseto ma valido anche sulle altre provincie.


![immagine](https://github.com/osmItalia/Segnalazioni-Mancata-attribuzione-OSM/assets/29042221/1927305b-f96d-42b9-b2eb-631316ad214b)
