### ISSUE TITLE
Mancata attribuzione a OSM - FreeCAD

### ISSUE THREAD

**Issue by FinixFighter** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#89]
# Descrizione
FreeCAD ha utilizzato OSM per indicare la posizione su mappa di un evento che terranno. L'articolo (preso dal loro blog) è stato più volte condiviso sui canale social dell'associazione, quindi teoricamente è stato visto da molte persone.

## Riferimento del prodotto senza attribuzione
La mappa in questione si trova in questo articolo: https://blog.freecad.org/2023/01/04/freecad-meeting-day-2023/

# Punto di contatto
L'associazione che gestisce FreeCAD è la FreeCAD Project Association (https://fpa.freecad.org/).
L'administration board può essere contattato tramite mail: [fpa@freecad.org](mailto:fpa@freecad.org) (come indicato su https://fpa.freecad.org/).
Sempre secondo lo stesso sito, un modo alternativo per contattare i membri dell'associazione è scrivergli tramite il loro forum (qui la lista dei membri: https://fpa.freecad.org/handbook/people/roster.html).

**Comment by LorenzoStucchi** [comment]
Essendo un associazione internazionale ho utilizzato questo format mail https://wiki.openstreetmap.org/wiki/Lacking_proper_attribution/Example_email

/remind me in 2 weeks
