### ISSUE TITLE
Mancata attribuzione a OSM - lasesia.it

### ISSUE THREAD

**Issue by musuruan** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#9]
# Descrizione
La cartina allegata all'articolo è una mappa OSM ed è priva di attribuzione.

## Riferimento del prodotto senza attibuzione
https://www.lasesia.it/vercelli/2021/07/27/news/semafori-via-xx-settembre-danno-importante-riparazione-non-immediata-106377/

# Punto di contatto
https://www.lasesia.it/sezioni/74/contatti

**Comment by LorenzoStucchi** [comment]
Inviata nuova mail usando tutti i contatti indicati nella pagina web

**Comment by LorenzoStucchi** [comment]
Risposta:

> Buongiorno, come da vostra richiesta (vedere allegato) abbiamo provveduto ad aggiungere in didascalia il link. Vogliamo però precisare che la foto ci era stata fornita dal Comune di Vercelli in allegato al comunicato.
> Grazie, buona giornata. La redazione
