### ISSUE TITLE
Mancata attribuzione a OSM - [Parco naturale regionale di Bracciano e Martignano]

### ISSUE THREAD

**Issue by DinoM65** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#90]
# Descrizione

Buongiono, come già precdentemente segnalato più volte , l'ente parco continua a produrre mappe escursionistiche senza l'attribuzione della base topografia a OSM. Questa volta il 25 febbraio hanno pubblicamente presentato una nuova carta che come le altre oltre non menziona OSM (https://it-it.facebook.com/parcobracciano). Ho verificato che in questa carta vi sono dei waypoint di siti archeologici così come l'area del poligono militare della Scuola di Fanteria di Cesano da me disegnati/caricati in OSM che non sono citati in nessuna altra mappa.

## Riferimento del prodotto senza attribuzione

# Punto di contatto

dbadaloni@regione.lazio.it - Daniele Badaloni direttore Parcoù
mscentoni@regione.lazio.it - Marco Scentoni coordinatore servizio Comunicazione

**Comment by LorenzoStucchi** [comment]
Per inviare la segnalazione è necessario un riferimento ad un prodotto senza attribuzione, un link se online o una foto se cartaceo

**Comment by LorenzoStucchi** [comment]
Ho trovato il post indicato https://www.facebook.com/photo/?fbid=570526025110661&set=pb.100064598053292.-2207520000

Rimanda ad un mappa gratuita fornita tramite l'app Avenza Maps. Come si mostra in foto sotto, la mappa è correttamente attribuita

![IMG_2206](https://github.com/osmItalia/Segnalazioni-Mancata-attribuzione-OSM/assets/29042221/28521122-e2d0-416e-b10a-1c81f803ece3)
