### ISSUE TITLE
Mancata attribuzione a OSM - [TED - Tuscia Esplorazione Divulgazione]

### ISSUE THREAD

**Issue by DinoM65** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#91]
# Descrizione

Sulla pagina facebook vi è notizia di una ennesima carta questa volta di Viterbo derivata da OSM senza fornire l'attribuzione

## Riferimento del prodotto senza attribuzione

https://www.facebook.com/photo/?fbid=535642005347881&set=pcb.535641522014596

# Punto di contatto

maupr76@gmail.com - gestore pagina facebook

**Comment by LorenzoStucchi** [comment]
La mappa risulta molto sgranata, in basso a destro sembra esserci una linea di testo, possibile sia una attribuzione. Vista la risuluzione risulta difficile assicurarsi che i dati siano stati presi da OSM
