### ISSUE TITLE
Mancata attribuzione a OSM - Applicazione autorizzata del Parco Archeologico di Pompei

### ISSUE THREAD

**Issue by oggioniale** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#92]
# Descrizione
Nell'applicazione (io provato solo su sistemi iPhone) del Parco Archeologico di Pompei (https://apps.apple.com/us/app/mypompeii/id1519515140) viene proposta la mappa dei diversi luoghi da visitare. La mappa è chiaramente una OSM e sovrapposti i luoghi da visitare.

## Riferimento del prodotto senza attribuzione
Allego qui screenshot del menù dal quale si accede alla mappa e della mappa stessa, dove si evince la non presenza della attribuzione.

![IMG_7735](https://user-images.githubusercontent.com/1393893/234936223-54790599-ae32-47a2-be34-e2fca66039b4.PNG)
![IMG_7736](https://user-images.githubusercontent.com/1393893/234936235-3ae19169-f921-4d0d-934d-2f63f1926d43.PNG)

# Punto di contatto
Sulla pagina dell'Apple store viene indicato che i diritti sulla applicazione sono del "Archaeological Park of Pompeii" e lo sviluppatore è lo stesso "Parco Archeologico di Pompei".
Da questa pagina si ha un link all'"App support" che rimanda a questa pagina http://pompeiisites.org/en/visiting-info/ dove si trovano indirizzo e-mail e pec. Rispettivamente: [pompei.info@cultura.gov.it](mailto:pompei.info@cultura.gov.it) e [pa-pompei@pec.cultura.gov.it](mailto:pa-pompei@pec.cultura.gov.it)

**Comment by LorenzoStucchi** [comment]
Inviata segnalazione via pec il 2 ottobre 2023
/remind me in 1 week

**Comment by LorenzoStucchi** [comment]
Considerati i 30 giorni di risposta alle pec, aspettiamo ancora altre 2 settimane prima di inviare nuova pec

/remind me in 2 weeks

**Comment by LorenzoStucchi** [comment]
Inviata nuova PEC 

/remind me in 30 days

**Comment by LorenzoStucchi** [comment]
Ancora nessuna risposta, ne a pec ne a telefonate

**Comment by oggioniale** [comment]
grave

**Comment by oggioniale** [comment]
Assurdo!
Speriamo che così si decidano a risolvere.

**Comment by LorenzoStucchi** [comment]
@oggioniale come previsto appena la minaccia è diventata più palese hanno risposto

> le scrivo in risposta al suo recente sollecito, in qualità di RUP dello sviluppo dell’app MyPompei, per comunicarle l’intenzione dell’amministrazione di procedere con la regolarizzazione di attribuzione "©OpenStreetMap contributors” come da lei indicato.
> Pertanto, considerato che l’intervento sull’app richiederà alcuni giorni, le chiedo di sospendere la procedura di sospensione di disponibilità delle mappe.
> Sarà mia cura comunicarle tempestivamente l’avvenuta regolarizzazione.
> Nel ringraziarla per la cortese disponibilità le invio Cordiali Saluti.

**Comment by oggioniale** [comment]
👍🏽

**Comment by LorenzoStucchi** [comment]
Viene mandata questa proposta, direi ottima. Aspettiamo che la implementino

![image](https://github.com/osmItalia/Segnalazioni-Mancata-attribuzione-OSM/assets/29042221/bc6da98f-3320-4b6b-ae22-5535c75c94aa)

**Comment by LorenzoStucchi** [comment]
Inviata di richiesta a seguito della mancanza di aggiornamenti. Risposta:

> la modifica è stata implementata su entrambe le versioni Android e IOS, venerdì 9 febbraio sera sarà inviata agli store per la loro approvazione.

Verificiare
/remind me in 1 week

**Comment by oggioniale** [comment]
@LorenzoStucchi ho provato a scaricare poco fa la applicazione in versione IOS ma ancora l'attribuzione è mancante:
![Screenshot 2024-02-07 (15 54 38)](https://github.com/osmItalia/Segnalazioni-Mancata-attribuzione-OSM/assets/1393893/a58c9400-fc43-4b5d-a8f2-6e50e0a5fb2a)

**Comment by LorenzoStucchi** [comment]
> @LorenzoStucchi ho provato a scaricare poco fa la applicazione in versione IOS ma ancora l'attribuzione è mancante: 

Si credo che verrà implementata nel weekend, quindi dovrebbe essere visibile da settimana prossima

**Comment by LorenzoStucchi** [comment]
L'app android risulta aggiornata, mentre l'app iOs non ancora

**Comment by LorenzoStucchi** [comment]
Segnalato errore su iOS, in giornata verificheranno

**Comment by LorenzoStucchi** [comment]
La correzione è diventata efficace anche su iOS

![IMG_FC44EBDA5A42-1](https://github.com/osmItalia/Segnalazioni-Mancata-attribuzione-OSM/assets/29042221/21987ba9-649d-4696-90e6-ca69055a11ea)

**Comment by oggioniale** [comment]
finalmente
