### ISSUE TITLE
Mancata attribuzione a OSM - mapcarta.com

### ISSUE THREAD

**Issue by e075e** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#93]
# Descrizione

nella mappa web è visibile facilmente solo l'attribuzione a mapbox in basso a sinistra, il riscontro dell'attribuzione OSM si ha solo:

- cliccando sull'icona (i) sopra l'attribuzione mapbox
- andando in fondo al pannello laterale di sinistra 

## Riferimento del prodotto senza attribuzione

`https://mapcarta.com/W886751022`

# Punto di contatto

mapcarta@mapcarta

`https://mapcarta.com/About_Mapcarta`

**Comment by LorenzoStucchi** [comment]
Pultroppo questa modalità è quella fornita da mapbox di base e non c'è niente di sbagliato
