### ISSUE TITLE
Mancata attribuzione a OSM - I sentieri di Gressoney

### ISSUE THREAD

**Issue by musuruan** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#95]
# Descrizione
Le mappe presenti sul sito https://www.sentierigressoney.it/ usano la opentopomap e sono tutte prive di attribuzione. 

## Riferimento del prodotto senza attribuzione

Alcuni esempio:
https://www.sentierigressoney.it/sentieri/gressoney-saint-jean-sentiero-12-colle-di-loo/
https://www.sentierigressoney.it/sentieri/gressoney-saint-jean-sentiero-14-saint-jean-trinite/

# Punto di contatto
info@sentierigressoney.it

**Comment by LorenzoStucchi** [comment]
Risposta:

> Buongiorno: ha perfettamente ragione, l'attribuzione c'è sempre stata, e sapevo benissimo fosse un requisito per l'utilizzo delle mappe. E'sparita per un problema con il plugin che sto usando: lo sviluppatore mi aveva suggerito di reinstallarlo, ma ho avuto finora paura a farlo perché temo di perdere gli infiniti settaggi... ma ha ragione, non posso esitare ulteriormente. Mi metto al lavoro oggi stesso, le invierò una mail non appena risolto il problema.
> 
> Colgo l'occasione per ringraziarvi del lavoro stupendo che fate, e mi scuso di nuovo per la trasgressione, dovuta unicamente a... pigrizia!

**Comment by LorenzoStucchi** [comment]
Correzione effettuata, le mappe risultano ora correttamente attribuite

![immagine](https://github.com/osmItalia/Segnalazioni-Mancata-attribuzione-OSM/assets/29042221/0748abc0-a8fa-471a-a8af-f8166abd4bf9)
