### ISSUE TITLE
Mancata attribuzione a OSM - [Sito del Comune di Voghera (PV)]

### ISSUE THREAD

**Issue by Max1234-Ita** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#97]
# Descrizione

Nel sito in oggetto è disponibile un'area dove si possono trovare informazioni storiche e turistiche sui monumenti nel territorio Comunale (esempio: https://www.comune.voghera.pv.it/it/page/castello-visconteo).
Ognuna di queste pagine contiene un link che permette di visualizzare il monumento selezionato in una mappa, che è chiaramente basata su cartografia OpenStreetMap: purtroppo, però, il leaflet che la implementa non contiene l'attribuzione richiesta.

## Riferimento del prodotto senza attribuzione

https://www.comune.voghera.pv.it/it/point-of-interests       e pagine successive (esempio: https://www.comune.voghera.pv.it/it/page/castello-visconteo)

![image](https://github.com/osmItalia/Segnalazioni-Mancata-attribuzione-OSM/assets/15315381/0bb55577-8062-4b3c-bf05-4f476cb06206)

![image](https://github.com/osmItalia/Segnalazioni-Mancata-attribuzione-OSM/assets/15315381/ffccc994-9a8f-4faf-8abc-0d7f3ae323fe)

# Punto di contatto

staff.sindaco@comune.voghera.pv.it - Staff del Sindaco
uff.informatica@comune.voghera.pv.it - Ufficio Informatica
protocollo@comune.voghera.pv.it - Contatto ufficiale riportato in calce alla home page

Il sito è creato da/con  di Municipium, purtroppo nel sito non ho trovato alcun riferimento al fornitore

**Comment by LorenzoStucchi** [comment]
Considerati gli obblighi di risposta dei comuni di 30 giorni. In attessa di ricevuta di protocollazione.

/remind me in 30 days

**Comment by LorenzoStucchi** [comment]
Risposta:

> Il sito è attualmente in fase di ristrutturazione per trasformarlo in modo che sia conforme alle linee guida di design di AGID.
> Per questo il fornitore sta introducendo gradualmente infrastrutture nel nuovo sito recuperando i dati dal vecchio.
> In queste operazioni può succedere che qualcosa sia da mettere a posto.
> Ho segnalato la problematica al nostro fornitore che ha ringraziato per la comunicazione e mi ha informato che farà le modifiche come segnalato dettagliatamente nella sua mail.
> Non mi ha fornito tempistiche precise ma penso che i tempi siano piuttosto brevi.

**Comment by LorenzoStucchi** [comment]
In alcune porzioni del sito risulta già corretto.

![immagine](https://github.com/osmItalia/Segnalazioni-Mancata-attribuzione-OSM/assets/29042221/1d045f33-1032-47b2-a56d-7016bc80ead8)

**Comment by Max1234-Ita** [comment]
Bene, dai.
Grazie!

**Comment by LorenzoStucchi** [comment]
L'attribuzione è comparsa in tutte le pagine, non sono stato notificato di questo, ma magari non si sono solamente ricordati

**Comment by Max1234-Ita** [comment]
Ciao Lorenzo, grazie!
