### ISSUE TITLE
Mancata attribuzione a OSM - Parkpedia

### ISSUE THREAD

**Issue by Martinligabue** [osmItalia/Segnalazioni-Mancata-attribuzione-OSM#99]
# Descrizione

La mappa di base è sicuramente presa da OSM, e ho dubbi pure i dati sui parcheggi siano tali. Non è presente alcuna attribuzione né sulla mappa né nelle pagine about, faq, etc.

## Riferimento del prodotto senza attribuzione

Qualsiasi ricerca in https://parkopedia.it

# Punto di contatto

Nessuna mail, ma c'è un modulo di contatto all'indirizzo seguente:
https://www.parkopedia.com/contact-us/

**Comment by LorenzoStucchi** [comment]
Attribuzione aggiunta

![immagine](https://github.com/osmItalia/Segnalazioni-Mancata-attribuzione-OSM/assets/29042221/03a8cb51-778d-4b31-a56c-ac761f3e7b13)
